import { describe, expect, it } from "vitest";
import {
  durableAuditActions,
  parseAuditLogProjection,
} from "./audit-event.server";

describe("audit event boundary", () => {
  it("keeps the durable action cohort intentionally small", () => {
    expect(durableAuditActions).toEqual([
      "access_grant.administrator_capacity_updated",
      "access_grant.administrator_code_revealed",
      "access_grant.administrator_created",
      "access_grant.administrator_revoked",
      "access_grant.owner_activated",
      "access_grant.owner_assigned",
      "access_grant.owner_code_revealed",
      "access_grant.owner_revoked",
      "authorization.platform_admin.bootstrapped",
      "authorization.platform_admin.granted",
      "authorization.platform_admin.invitation_cancelled",
      "authorization.platform_admin.invited",
      "authorization.platform_admin.revoked",
      "course.archived",
      "course.created",
      "course.deleted",
      "course.published",
      "course.version_created",
      "communication_plan.created",
      "communication_plan.deleted",
      "communication_plan.overridden",
      "communication_plan.reset",
      "communication_plan.updated",
      "email_design.created",
      "email_design.draft_created",
      "email_design.draft_deleted",
      "email_design.published",
      "email_design.reordered",
      "email_design.rolled_back",
      "enterprise_contract.activated",
      "enterprise_contract.bulk_enrollment_completed",
      "enterprise_contract.claimed",
      "enterprise_contract.code_rotated",
      "enterprise_contract.code_revealed",
      "enterprise_contract.created",
      "enterprise_contract.eligibility_replaced",
      "enterprise_contract.entitlement_issued",
      "enterprise_contract.event_registered",
      "enterprise_contract.owner_activated",
      "enterprise_contract.owner_assigned",
      "enterprise_contract.owner_revoked",
      "enterprise_contract.renewed",
      "enterprise_contract.report_exported",
      "enterprise_contract.resumed",
      "enterprise_contract.suspended",
      "enterprise_contract.terminated",
      "event_occurrence.created",
      "event_occurrence.guest_access_rotated",
      "event_occurrence.updated",
      "event_occurrence.published",
      "event_occurrence.lifecycle_changed",
      "event_occurrence.rescheduled",
      "event_participation.completed",
      "event_participation.completion_revoked",
      "event_staff.eligibility_granted",
      "event_staff.eligibility_revoked",
      "coordination_region.created",
      "coordination_region.updated",
      "coordination_region.retired",
      "coordination_region.reactivated",
      "event_attendance.recorded",
      "event_late_registration_invitation.accepted",
      "event_late_registration_invitation.created",
      "event_late_registration_invitation.revoked",
      "event_prerequisite.recovery_verified",
      "event_region_review.locked",
      "event_registration.administrator_added",
      "event_registration.coordinator_reviewed",
      "event_registration.final_decided",
      "event_registration.region_mismatch_acknowledged",
      "event_registration.region_decided",
      "event_registration.region_reassigned",
      "event_registration.submitted",
      "event_registration.withdrawn",
      "event_template.created",
      "event_template.draft_deleted",
      "event_template.version_created",
      "event_template.version_published",
      "event_virtual_room.created",
      "event_virtual_room.lifecycle_changed",
      "event_virtual_room.presenter_token_issued",
      "enrollment.access_code_redeemed",
      "enrollment.administrator_added",
      "enrollment.administrator_removed",
      "enrollment.learning_completed",
      "enrollment.purchased",
      "enrollment.scorm_completed",
      "entitlement.information_release_accepted",
      "notification.delivery_requeued",
      "order.checkout_failed",
      "order.checkout_paid",
      "order.paid_existing_enrollment",
      "order.refund_recorded",
      "resource.uploaded",
      "resource.version_removed",
      "registration_questionnaire.waived",
      "scorm.package_uploaded",
      "scorm.package_version_removed",
      "survey.created",
      "survey.published",
      "survey.reordered",
      "survey.version_created",
      "user.account_activated",
      "user.account_setup_resent",
      "user.provisional_created",
      "user.onboarding_reassigned",
      "user.phone_verification_transferred",
      "user.region_updated",
    ]);
  });

  it("accepts only versioned, known, scalar audit projections", () => {
    expect(
      parseAuditLogProjection({
        version: 1,
        eventId: "audit_1",
        event: "order.checkout_paid",
        actorUserId: "user_1",
        entityType: "order",
        entityId: "order_1",
        aggregateId: "order_1",
        outcome: "succeeded",
      }),
    ).toMatchObject({ eventId: "audit_1", event: "order.checkout_paid" });

    expect(() =>
      parseAuditLogProjection({
        version: 1,
        eventId: "audit_2",
        event: "unknown.event",
        actorUserId: null,
        entityType: "order",
        entityId: "order_2",
        aggregateId: "order_2",
      }),
    ).toThrow();
  });
});
