/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessManagementRouteImport } from './routes/access-management'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EventInvitationRouteImport } from './routes/event-invitation'
import { Route as EventOperationsRouteImport } from './routes/event-operations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AccountSetupRouteImport } from './routes/account.setup'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAccessRouteImport } from './routes/admin.access'
import { Route as AdminAdministratorsRouteImport } from './routes/admin.administrators'
import { Route as AdminContractsRouteImport } from './routes/admin.contracts'
import { Route as AdminModulesRouteImport } from './routes/admin.modules'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminOnboardingRouteImport } from './routes/admin.onboarding'
import { Route as AdminResourcesRouteImport } from './routes/admin.resources'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as EventAccessPublicReferenceRouteImport } from './routes/event-access.$publicReference'
import { Route as EventOperationsIndexRouteImport } from './routes/event-operations.index'
import { Route as EventOperationsEventOccurrenceIdRouteImport } from './routes/event-operations.$eventOccurrenceId'
import { Route as EventSurveysPublicReferenceRouteImport } from './routes/event-surveys.$publicReference'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as LearnEnrollmentIdRouteImport } from './routes/learn.$enrollmentId'
import { Route as MyEventsEventOccurrenceIdRouteImport } from './routes/my-events_.$eventOccurrenceId'
import { Route as AdminContractsNewRouteImport } from './routes/admin.contracts_.new'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin.courses.index'
import { Route as AdminCoursesCourseIdRouteImport } from './routes/admin.courses.$courseId'
import { Route as AdminEmailsIndexRouteImport } from './routes/admin.emails.index'
import { Route as AdminEmailsEmailDesignIdRouteImport } from './routes/admin.emails.$emailDesignId'
import { Route as AdminEventsIndexRouteImport } from './routes/admin.events.index'
import { Route as AdminEventsEventTemplateIdRouteImport } from './routes/admin.events.$eventTemplateId'
import { Route as AdminEventsScheduledRouteImport } from './routes/admin.events.scheduled'
import { Route as AdminEventsSettingsRouteImport } from './routes/admin.events.settings'
import { Route as AdminEventsTemplatesRouteImport } from './routes/admin.events.templates'
import { Route as AdminLearnersIndexRouteImport } from './routes/admin.learners.index'
import { Route as AdminLearnersUserIdRouteImport } from './routes/admin.learners.$userId'
import { Route as AdminSurveysIndexRouteImport } from './routes/admin.surveys.index'
import { Route as AdminSurveysSurveyIdRouteImport } from './routes/admin.surveys.$surveyId'
import { Route as ApiAdminAccreditationLogosRouteImport } from './routes/api.admin.accreditation-logos'
import { Route as ApiAdminOfferingImagesRouteImport } from './routes/api.admin.offering-images'
import { Route as ApiAdminResourcesRouteImport } from './routes/api.admin.resources'
import { Route as ApiAdminScormPackagesRouteImport } from './routes/api.admin.scorm-packages'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiLivekitWebhookRouteImport } from './routes/api.livekit.webhook'
import { Route as ApiScormLaunchRouteImport } from './routes/api.scorm.launch'
import { Route as ApiScormLaunchesRouteImport } from './routes/api.scorm.launches'
import { Route as ApiScormPreviewRouteImport } from './routes/api.scorm.preview'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'
import { Route as ApiTextbeeWebhookRouteImport } from './routes/api.textbee.webhook'
import { Route as CoursesSlugBulkOrderRouteImport } from './routes/courses.$slug_.bulk-order'
import { Route as EventsSlugBulkOrderRouteImport } from './routes/events.$slug_.bulk-order'
import { Route as AdminEventsInstancesEventOccurrenceIdRouteImport } from './routes/admin.events.instances.$eventOccurrenceId'
import { Route as AdminEventsInstancesNewRouteImport } from './routes/admin.events.instances_.new'
import { Route as ApiAccessManagementAccessGrantIdCodesDotcsvRouteImport } from './routes/api.access-management.$accessGrantId.codes[.]csv'
import { Route as ApiAccessManagementAccessGrantIdLearnersDotcsvRouteImport } from './routes/api.access-management.$accessGrantId.learners[.]csv'
import { Route as ApiAdminOfferingImagesAssetIdRouteImport } from './routes/api.admin.offering-images.$assetId'
import { Route as ApiEventOperationsEventOccurrenceIdProgressDotcsvRouteImport } from './routes/api.event-operations.$eventOccurrenceId.progress[.]csv'
import { Route as ApiEventSurveysPublicReferenceQrDotsvgRouteImport } from './routes/api.event-surveys.$publicReference.qr[.]svg'
import { Route as ApiLearningCertificatesEnrollmentIdRouteImport } from './routes/api.learning.certificates.$enrollmentId'
import { Route as ApiLearningEventCertificatesEventParticipationIdRouteImport } from './routes/api.learning.event-certificates.$eventParticipationId'
import { Route as ApiLearningResourcesResourceVersionIdRouteImport } from './routes/api.learning.resources.$resourceVersionId'
import { Route as ApiScormAttemptsAttemptIdRouteImport } from './routes/api.scorm.attempts.$attemptId'
import { Route as ApiScormPreviewsPackageVersionIdRouteImport } from './routes/api.scorm.previews.$packageVersionId'
import { Route as EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRouteImport } from './routes/event-operations.$eventOccurrenceId_.survey-qr.$eventSurveyAccessId'
import { Route as LearnEnrollmentIdSurveysCourseVersionItemIdRouteImport } from './routes/learn.$enrollmentId_.surveys.$courseVersionItemId'
import { Route as MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRouteImport } from './routes/my-events_.$eventOccurrenceId_.surveys.$eventTemplateVersionItemId'
import { Route as AdminLearnersUserIdEnrollmentsEnrollmentIdRouteImport } from './routes/admin.learners.$userId_.enrollments.$enrollmentId'
import { Route as AdminLearnersUserIdEventsEventOccurrenceIdRouteImport } from './routes/admin.learners.$userId_.events.$eventOccurrenceId'
import { Route as ApiAccessManagementContractsEnterpriseContractIdUtilisationDotcsvRouteImport } from './routes/api.access-management.contracts.$enterpriseContractId.utilisation[.]csv'
import { Route as ApiAdminContractsEnterpriseContractIdUtilisationDotcsvRouteImport } from './routes/api.admin.contracts.$enterpriseContractId.utilisation[.]csv'
import { Route as ApiAdminScormPackagesPackageVersionIdPreviewRouteImport } from './routes/api.admin.scorm-packages.$packageVersionId.preview'
import { Route as ApiCatalogCoursesSlugAccreditationLogosAssetIdRouteImport } from './routes/api.catalog.courses.$slug.accreditation-logos.$assetId'
import { Route as ApiCatalogCoursesSlugCoverImagesAssetIdRouteImport } from './routes/api.catalog.courses.$slug.cover-images.$assetId'
import { Route as ApiCatalogEventsSlugAccreditationLogosAssetIdRouteImport } from './routes/api.catalog.events.$slug.accreditation-logos.$assetId'
import { Route as ApiCatalogEventsSlugCoverImagesAssetIdRouteImport } from './routes/api.catalog.events.$slug.cover-images.$assetId'
import { Route as ApiScormAttemptsAttemptIdContentSplatRouteImport } from './routes/api.scorm.attempts.$attemptId.content.$'
import { Route as ApiScormPreviewsPackageVersionIdContentSplatRouteImport } from './routes/api.scorm.previews.$packageVersionId.content.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessManagementRoute = AccessManagementRouteImport.update({
  id: '/access-management',
  path: '/access-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EventInvitationRoute = EventInvitationRouteImport.update({
  id: '/event-invitation',
  path: '/event-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const EventOperationsRoute = EventOperationsRouteImport.update({
  id: '/event-operations',
  path: '/event-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSetupRoute = AccountSetupRouteImport.update({
  id: '/account/setup',
  path: '/account/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdministratorsRoute = AdminAdministratorsRouteImport.update({
  id: '/administrators',
  path: '/administrators',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContractsRoute = AdminContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnboardingRoute = AdminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AdminRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventAccessPublicReferenceRoute =
  EventAccessPublicReferenceRouteImport.update({
    id: '/event-access/$publicReference',
    path: '/event-access/$publicReference',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventOperationsIndexRoute = EventOperationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventOperationsRoute,
} as any)
const EventOperationsEventOccurrenceIdRoute =
  EventOperationsEventOccurrenceIdRouteImport.update({
    id: '/$eventOccurrenceId',
    path: '/$eventOccurrenceId',
    getParentRoute: () => EventOperationsRoute,
  } as any)
const EventSurveysPublicReferenceRoute =
  EventSurveysPublicReferenceRouteImport.update({
    id: '/event-surveys/$publicReference',
    path: '/event-surveys/$publicReference',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnEnrollmentIdRoute = LearnEnrollmentIdRouteImport.update({
  id: '/learn/$enrollmentId',
  path: '/learn/$enrollmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsEventOccurrenceIdRoute =
  MyEventsEventOccurrenceIdRouteImport.update({
    id: '/my-events_/$eventOccurrenceId',
    path: '/my-events/$eventOccurrenceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContractsNewRoute = AdminContractsNewRouteImport.update({
  id: '/contracts_/new',
  path: '/contracts/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesCourseIdRoute = AdminCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsIndexRoute = AdminEmailsIndexRouteImport.update({
  id: '/emails/',
  path: '/emails/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsEmailDesignIdRoute =
  AdminEmailsEmailDesignIdRouteImport.update({
    id: '/emails/$emailDesignId',
    path: '/emails/$emailDesignId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsEventTemplateIdRoute =
  AdminEventsEventTemplateIdRouteImport.update({
    id: '/events/$eventTemplateId',
    path: '/events/$eventTemplateId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEventsScheduledRoute = AdminEventsScheduledRouteImport.update({
  id: '/events/scheduled',
  path: '/events/scheduled',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsSettingsRoute = AdminEventsSettingsRouteImport.update({
  id: '/events/settings',
  path: '/events/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsTemplatesRoute = AdminEventsTemplatesRouteImport.update({
  id: '/events/templates',
  path: '/events/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLearnersIndexRoute = AdminLearnersIndexRouteImport.update({
  id: '/learners/',
  path: '/learners/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLearnersUserIdRoute = AdminLearnersUserIdRouteImport.update({
  id: '/learners/$userId',
  path: '/learners/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSurveysIndexRoute = AdminSurveysIndexRouteImport.update({
  id: '/surveys/',
  path: '/surveys/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSurveysSurveyIdRoute = AdminSurveysSurveyIdRouteImport.update({
  id: '/surveys/$surveyId',
  path: '/surveys/$surveyId',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminAccreditationLogosRoute =
  ApiAdminAccreditationLogosRouteImport.update({
    id: '/api/admin/accreditation-logos',
    path: '/api/admin/accreditation-logos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminOfferingImagesRoute = ApiAdminOfferingImagesRouteImport.update({
  id: '/api/admin/offering-images',
  path: '/api/admin/offering-images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminResourcesRoute = ApiAdminResourcesRouteImport.update({
  id: '/api/admin/resources',
  path: '/api/admin/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminScormPackagesRoute = ApiAdminScormPackagesRouteImport.update({
  id: '/api/admin/scorm-packages',
  path: '/api/admin/scorm-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLivekitWebhookRoute = ApiLivekitWebhookRouteImport.update({
  id: '/api/livekit/webhook',
  path: '/api/livekit/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScormLaunchRoute = ApiScormLaunchRouteImport.update({
  id: '/api/scorm/launch',
  path: '/api/scorm/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScormLaunchesRoute = ApiScormLaunchesRouteImport.update({
  id: '/api/scorm/launches',
  path: '/api/scorm/launches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScormPreviewRoute = ApiScormPreviewRouteImport.update({
  id: '/api/scorm/preview',
  path: '/api/scorm/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTextbeeWebhookRoute = ApiTextbeeWebhookRouteImport.update({
  id: '/api/textbee/webhook',
  path: '/api/textbee/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugBulkOrderRoute = CoursesSlugBulkOrderRouteImport.update({
  id: '/courses/$slug_/bulk-order',
  path: '/courses/$slug/bulk-order',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugBulkOrderRoute = EventsSlugBulkOrderRouteImport.update({
  id: '/events/$slug_/bulk-order',
  path: '/events/$slug/bulk-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsInstancesEventOccurrenceIdRoute =
  AdminEventsInstancesEventOccurrenceIdRouteImport.update({
    id: '/events/instances/$eventOccurrenceId',
    path: '/events/instances/$eventOccurrenceId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEventsInstancesNewRoute = AdminEventsInstancesNewRouteImport.update({
  id: '/events/instances_/new',
  path: '/events/instances/new',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAccessManagementAccessGrantIdCodesDotcsvRoute =
  ApiAccessManagementAccessGrantIdCodesDotcsvRouteImport.update({
    id: '/api/access-management/$accessGrantId/codes.csv',
    path: '/api/access-management/$accessGrantId/codes.csv',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAccessManagementAccessGrantIdLearnersDotcsvRoute =
  ApiAccessManagementAccessGrantIdLearnersDotcsvRouteImport.update({
    id: '/api/access-management/$accessGrantId/learners.csv',
    path: '/api/access-management/$accessGrantId/learners.csv',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminOfferingImagesAssetIdRoute =
  ApiAdminOfferingImagesAssetIdRouteImport.update({
    id: '/$assetId',
    path: '/$assetId',
    getParentRoute: () => ApiAdminOfferingImagesRoute,
  } as any)
const ApiEventOperationsEventOccurrenceIdProgressDotcsvRoute =
  ApiEventOperationsEventOccurrenceIdProgressDotcsvRouteImport.update({
    id: '/api/event-operations/$eventOccurrenceId/progress.csv',
    path: '/api/event-operations/$eventOccurrenceId/progress.csv',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEventSurveysPublicReferenceQrDotsvgRoute =
  ApiEventSurveysPublicReferenceQrDotsvgRouteImport.update({
    id: '/api/event-surveys/$publicReference/qr.svg',
    path: '/api/event-surveys/$publicReference/qr.svg',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLearningCertificatesEnrollmentIdRoute =
  ApiLearningCertificatesEnrollmentIdRouteImport.update({
    id: '/api/learning/certificates/$enrollmentId',
    path: '/api/learning/certificates/$enrollmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLearningEventCertificatesEventParticipationIdRoute =
  ApiLearningEventCertificatesEventParticipationIdRouteImport.update({
    id: '/api/learning/event-certificates/$eventParticipationId',
    path: '/api/learning/event-certificates/$eventParticipationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLearningResourcesResourceVersionIdRoute =
  ApiLearningResourcesResourceVersionIdRouteImport.update({
    id: '/api/learning/resources/$resourceVersionId',
    path: '/api/learning/resources/$resourceVersionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiScormAttemptsAttemptIdRoute =
  ApiScormAttemptsAttemptIdRouteImport.update({
    id: '/api/scorm/attempts/$attemptId',
    path: '/api/scorm/attempts/$attemptId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiScormPreviewsPackageVersionIdRoute =
  ApiScormPreviewsPackageVersionIdRouteImport.update({
    id: '/api/scorm/previews/$packageVersionId',
    path: '/api/scorm/previews/$packageVersionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRoute =
  EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRouteImport.update(
    {
      id: '/$eventOccurrenceId_/survey-qr/$eventSurveyAccessId',
      path: '/$eventOccurrenceId/survey-qr/$eventSurveyAccessId',
      getParentRoute: () => EventOperationsRoute,
    } as any,
  )
const LearnEnrollmentIdSurveysCourseVersionItemIdRoute =
  LearnEnrollmentIdSurveysCourseVersionItemIdRouteImport.update({
    id: '/learn/$enrollmentId_/surveys/$courseVersionItemId',
    path: '/learn/$enrollmentId/surveys/$courseVersionItemId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRoute =
  MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRouteImport.update({
    id: '/my-events_/$eventOccurrenceId_/surveys/$eventTemplateVersionItemId',
    path: '/my-events/$eventOccurrenceId/surveys/$eventTemplateVersionItemId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminLearnersUserIdEnrollmentsEnrollmentIdRoute =
  AdminLearnersUserIdEnrollmentsEnrollmentIdRouteImport.update({
    id: '/learners/$userId_/enrollments/$enrollmentId',
    path: '/learners/$userId/enrollments/$enrollmentId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminLearnersUserIdEventsEventOccurrenceIdRoute =
  AdminLearnersUserIdEventsEventOccurrenceIdRouteImport.update({
    id: '/learners/$userId_/events/$eventOccurrenceId',
    path: '/learners/$userId/events/$eventOccurrenceId',
    getParentRoute: () => AdminRoute,
  } as any)
const ApiAccessManagementContractsEnterpriseContractIdUtilisationDotcsvRoute =
  ApiAccessManagementContractsEnterpriseContractIdUtilisationDotcsvRouteImport.update(
    {
      id: '/api/access-management/contracts/$enterpriseContractId/utilisation.csv',
      path: '/api/access-management/contracts/$enterpriseContractId/utilisation.csv',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const ApiAdminContractsEnterpriseContractIdUtilisationDotcsvRoute =
  ApiAdminContractsEnterpriseContractIdUtilisationDotcsvRouteImport.update({
    id: '/api/admin/contracts/$enterpriseContractId/utilisation.csv',
    path: '/api/admin/contracts/$enterpriseContractId/utilisation.csv',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminScormPackagesPackageVersionIdPreviewRoute =
  ApiAdminScormPackagesPackageVersionIdPreviewRouteImport.update({
    id: '/$packageVersionId/preview',
    path: '/$packageVersionId/preview',
    getParentRoute: () => ApiAdminScormPackagesRoute,
  } as any)
const ApiCatalogCoursesSlugAccreditationLogosAssetIdRoute =
  ApiCatalogCoursesSlugAccreditationLogosAssetIdRouteImport.update({
    id: '/api/catalog/courses/$slug/accreditation-logos/$assetId',
    path: '/api/catalog/courses/$slug/accreditation-logos/$assetId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCatalogCoursesSlugCoverImagesAssetIdRoute =
  ApiCatalogCoursesSlugCoverImagesAssetIdRouteImport.update({
    id: '/api/catalog/courses/$slug/cover-images/$assetId',
    path: '/api/catalog/courses/$slug/cover-images/$assetId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCatalogEventsSlugAccreditationLogosAssetIdRoute =
  ApiCatalogEventsSlugAccreditationLogosAssetIdRouteImport.update({
    id: '/api/catalog/events/$slug/accreditation-logos/$assetId',
    path: '/api/catalog/events/$slug/accreditation-logos/$assetId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCatalogEventsSlugCoverImagesAssetIdRoute =
  ApiCatalogEventsSlugCoverImagesAssetIdRouteImport.update({
    id: '/api/catalog/events/$slug/cover-images/$assetId',
    path: '/api/catalog/events/$slug/cover-images/$assetId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiScormAttemptsAttemptIdContentSplatRoute =
  ApiScormAttemptsAttemptIdContentSplatRouteImport.update({
    id: '/content/$',
    path: '/content/$',
    getParentRoute: () => ApiScormAttemptsAttemptIdRoute,
  } as any)
const ApiScormPreviewsPackageVersionIdContentSplatRoute =
  ApiScormPreviewsPackageVersionIdContentSplatRouteImport.update({
    id: '/content/$',
    path: '/content/$',
    getParentRoute: () => ApiScormPreviewsPackageVersionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-management': typeof AccessManagementRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/event-invitation': typeof EventInvitationRoute
  '/event-operations': typeof EventOperationsRouteWithChildren
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/account/setup': typeof AccountSetupRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/administrators': typeof AdminAdministratorsRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/api/health': typeof ApiHealthRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/event-access/$publicReference': typeof EventAccessPublicReferenceRoute
  '/event-operations/$eventOccurrenceId': typeof EventOperationsEventOccurrenceIdRoute
  '/event-surveys/$publicReference': typeof EventSurveysPublicReferenceRoute
  '/events/$slug': typeof EventsSlugRoute
  '/learn/$enrollmentId': typeof LearnEnrollmentIdRoute
  '/my-events/$eventOccurrenceId': typeof MyEventsEventOccurrenceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/event-operations/': typeof EventOperationsIndexRoute
  '/admin/contracts/new': typeof AdminContractsNewRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/emails/$emailDesignId': typeof AdminEmailsEmailDesignIdRoute
  '/admin/events/$eventTemplateId': typeof AdminEventsEventTemplateIdRoute
  '/admin/events/scheduled': typeof AdminEventsScheduledRoute
  '/admin/events/settings': typeof AdminEventsSettingsRoute
  '/admin/events/templates': typeof AdminEventsTemplatesRoute
  '/admin/learners/$userId': typeof AdminLearnersUserIdRoute
  '/admin/surveys/$surveyId': typeof AdminSurveysSurveyIdRoute
  '/api/admin/accreditation-logos': typeof ApiAdminAccreditationLogosRoute
  '/api/admin/offering-images': typeof ApiAdminOfferingImagesRouteWithChildren
  '/api/admin/resources': typeof ApiAdminResourcesRoute
  '/api/admin/scorm-packages': typeof ApiAdminScormPackagesRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/livekit/webhook': typeof ApiLivekitWebhookRoute
  '/api/scorm/launch': typeof ApiScormLaunchRoute
  '/api/scorm/launches': typeof ApiScormLaunchesRoute
  '/api/scorm/preview': typeof ApiScormPreviewRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/textbee/webhook': typeof ApiTextbeeWebhookRoute
  '/courses/$slug/bulk-order': typeof CoursesSlugBulkOrderRoute
  '/events/$slug/bulk-order': typeof EventsSlugBulkOrderRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/emails/': typeof AdminEmailsIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/learners/': typeof AdminLearnersIndexRoute
  '/admin/surveys/': typeof AdminSurveysIndexRoute
  '/admin/events/instances/$eventOccurrenceId': typeof AdminEventsInstancesEventOccurrenceIdRoute
  '/admin/events/instances/new': typeof AdminEventsInstancesNewRoute
  '/api/access-management/$accessGrantId/codes.csv': typeof ApiAccessManagementAccessGrantIdCodesDotcsvRoute
  '/api/access-management/$accessGrantId/learners.csv': typeof ApiAccessManagementAccessGrantIdLearnersDotcsvRoute
  '/api/admin/offering-images/$assetId': typeof ApiAdminOfferingImagesAssetIdRoute
  '/api/event-operations/$eventOccurrenceId/progress.csv': typeof ApiEventOperationsEventOccurrenceIdProgressDotcsvRoute
  '/api/event-surveys/$publicReference/qr.svg': typeof ApiEventSurveysPublicReferenceQrDotsvgRoute
  '/api/learning/certificates/$enrollmentId': typeof ApiLearningCertificatesEnrollmentIdRoute
  '/api/learning/event-certificates/$eventParticipationId': typeof ApiLearningEventCertificatesEventParticipationIdRoute
  '/api/learning/resources/$resourceVersionId': typeof ApiLearningResourcesResourceVersionIdRoute
  '/api/scorm/attempts/$attemptId': typeof ApiScormAttemptsAttemptIdRouteWithChildren
  '/api/scorm/previews/$packageVersionId': typeof ApiScormPreviewsPackageVersionIdRouteWithChildren
  '/event-operations/$eventOccurrenceId/survey-qr/$eventSurveyAccessId': typeof EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRoute
  '/learn/$enrollmentId/surveys/$courseVersionItemId': typeof LearnEnrollmentIdSurveysCourseVersionItemIdRoute
  '/my-events/$eventOccurrenceId/surveys/$eventTemplateVersionItemId': typeof MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRoute
  '/admin/learners/$userId/enrollments/$enrollmentId': typeof AdminLearnersUserIdEnrollmentsEnrollmentIdRoute
  '/admin/learners/$userId/events/$eventOccurrenceId': typeof AdminLearnersUserIdEventsEventOccurrenceIdRoute
  '/api/access-management/contracts/$enterpriseContractId/utilisation.csv': typeof ApiAccessManagementContractsEnterpriseContractIdUtilisationDotcsvRoute
  '/api/admin/contracts/$enterpriseContractId/utilisation.csv': typeof ApiAdminContractsEnterpriseContractIdUtilisationDotcsvRoute
  '/api/admin/scorm-packages/$packageVersionId/preview': typeof ApiAdminScormPackagesPackageVersionIdPreviewRoute
  '/api/catalog/courses/$slug/accreditation-logos/$assetId': typeof ApiCatalogCoursesSlugAccreditationLogosAssetIdRoute
  '/api/catalog/courses/$slug/cover-images/$assetId': typeof ApiCatalogCoursesSlugCoverImagesAssetIdRoute
  '/api/catalog/events/$slug/accreditation-logos/$assetId': typeof ApiCatalogEventsSlugAccreditationLogosAssetIdRoute
  '/api/catalog/events/$slug/cover-images/$assetId': typeof ApiCatalogEventsSlugCoverImagesAssetIdRoute
  '/api/scorm/attempts/$attemptId/content/$': typeof ApiScormAttemptsAttemptIdContentSplatRoute
  '/api/scorm/previews/$packageVersionId/content/$': typeof ApiScormPreviewsPackageVersionIdContentSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-management': typeof AccessManagementRoute
  '/dashboard': typeof DashboardRoute
  '/event-invitation': typeof EventInvitationRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/account/setup': typeof AccountSetupRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/administrators': typeof AdminAdministratorsRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/api/health': typeof ApiHealthRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/event-access/$publicReference': typeof EventAccessPublicReferenceRoute
  '/event-operations/$eventOccurrenceId': typeof EventOperationsEventOccurrenceIdRoute
  '/event-surveys/$publicReference': typeof EventSurveysPublicReferenceRoute
  '/events/$slug': typeof EventsSlugRoute
  '/learn/$enrollmentId': typeof LearnEnrollmentIdRoute
  '/my-events/$eventOccurrenceId': typeof MyEventsEventOccurrenceIdRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/event-operations': typeof EventOperationsIndexRoute
  '/admin/contracts/new': typeof AdminContractsNewRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/emails/$emailDesignId': typeof AdminEmailsEmailDesignIdRoute
  '/admin/events/$eventTemplateId': typeof AdminEventsEventTemplateIdRoute
  '/admin/events/scheduled': typeof AdminEventsScheduledRoute
  '/admin/events/settings': typeof AdminEventsSettingsRoute
  '/admin/events/templates': typeof AdminEventsTemplatesRoute
  '/admin/learners/$userId': typeof AdminLearnersUserIdRoute
  '/admin/surveys/$surveyId': typeof AdminSurveysSurveyIdRoute
  '/api/admin/accreditation-logos': typeof ApiAdminAccreditationLogosRoute
  '/api/admin/offering-images': typeof ApiAdminOfferingImagesRouteWithChildren
  '/api/admin/resources': typeof ApiAdminResourcesRoute
  '/api/admin/scorm-packages': typeof ApiAdminScormPackagesRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/livekit/webhook': typeof ApiLivekitWebhookRoute
  '/api/scorm/launch': typeof ApiScormLaunchRoute
  '/api/scorm/launches': typeof ApiScormLaunchesRoute
  '/api/scorm/preview': typeof ApiScormPreviewRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/textbee/webhook': typeof ApiTextbeeWebhookRoute
  '/courses/$slug/bulk-order': typeof CoursesSlugBulkOrderRoute
  '/events/$slug/bulk-order': typeof EventsSlugBulkOrderRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/emails': typeof AdminEmailsIndexRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/learners': typeof AdminLearnersIndexRoute
  '/admin/surveys': typeof AdminSurveysIndexRoute
  '/admin/events/instances/$eventOccurrenceId': typeof AdminEventsInstancesEventOccurrenceIdRoute
  '/admin/events/instances/new': typeof AdminEventsInstancesNewRoute
  '/api/access-management/$accessGrantId/codes.csv': typeof ApiAccessManagementAccessGrantIdCodesDotcsvRoute
  '/api/access-management/$accessGrantId/learners.csv': typeof ApiAccessManagementAccessGrantIdLearnersDotcsvRoute
  '/api/admin/offering-images/$assetId': typeof ApiAdminOfferingImagesAssetIdRoute
  '/api/event-operations/$eventOccurrenceId/progress.csv': typeof ApiEventOperationsEventOccurrenceIdProgressDotcsvRoute
  '/api/event-surveys/$publicReference/qr.svg': typeof ApiEventSurveysPublicReferenceQrDotsvgRoute
  '/api/learning/certificates/$enrollmentId': typeof ApiLearningCertificatesEnrollmentIdRoute
  '/api/learning/event-certificates/$eventParticipationId': typeof ApiLearningEventCertificatesEventParticipationIdRoute
  '/api/learning/resources/$resourceVersionId': typeof ApiLearningResourcesResourceVersionIdRoute
  '/api/scorm/attempts/$attemptId': typeof ApiScormAttemptsAttemptIdRouteWithChildren
  '/api/scorm/previews/$packageVersionId': typeof ApiScormPreviewsPackageVersionIdRouteWithChildren
  '/event-operations/$eventOccurrenceId/survey-qr/$eventSurveyAccessId': typeof EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRoute
  '/learn/$enrollmentId/surveys/$courseVersionItemId': typeof LearnEnrollmentIdSurveysCourseVersionItemIdRoute
  '/my-events/$eventOccurrenceId/surveys/$eventTemplateVersionItemId': typeof MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRoute
  '/admin/learners/$userId/enrollments/$enrollmentId': typeof AdminLearnersUserIdEnrollmentsEnrollmentIdRoute
  '/admin/learners/$userId/events/$eventOccurrenceId': typeof AdminLearnersUserIdEventsEventOccurrenceIdRoute
  '/api/access-management/contracts/$enterpriseContractId/utilisation.csv': typeof ApiAccessManagementContractsEnterpriseContractIdUtilisationDotcsvRoute
  '/api/admin/contracts/$enterpriseContractId/utilisation.csv': typeof ApiAdminContractsEnterpriseContractIdUtilisationDotcsvRoute
  '/api/admin/scorm-packages/$packageVersionId/preview': typeof ApiAdminScormPackagesPackageVersionIdPreviewRoute
  '/api/catalog/courses/$slug/accreditation-logos/$assetId': typeof ApiCatalogCoursesSlugAccreditationLogosAssetIdRoute
  '/api/catalog/courses/$slug/cover-images/$assetId': typeof ApiCatalogCoursesSlugCoverImagesAssetIdRoute
  '/api/catalog/events/$slug/accreditation-logos/$assetId': typeof ApiCatalogEventsSlugAccreditationLogosAssetIdRoute
  '/api/catalog/events/$slug/cover-images/$assetId': typeof ApiCatalogEventsSlugCoverImagesAssetIdRoute
  '/api/scorm/attempts/$attemptId/content/$': typeof ApiScormAttemptsAttemptIdContentSplatRoute
  '/api/scorm/previews/$packageVersionId/content/$': typeof ApiScormPreviewsPackageVersionIdContentSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-management': typeof AccessManagementRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/event-invitation': typeof EventInvitationRoute
  '/event-operations': typeof EventOperationsRouteWithChildren
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/account/setup': typeof AccountSetupRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/administrators': typeof AdminAdministratorsRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/api/health': typeof ApiHealthRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/event-access/$publicReference': typeof EventAccessPublicReferenceRoute
  '/event-operations/$eventOccurrenceId': typeof EventOperationsEventOccurrenceIdRoute
  '/event-surveys/$publicReference': typeof EventSurveysPublicReferenceRoute
  '/events/$slug': typeof EventsSlugRoute
  '/learn/$enrollmentId': typeof LearnEnrollmentIdRoute
  '/my-events_/$eventOccurrenceId': typeof MyEventsEventOccurrenceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/event-operations/': typeof EventOperationsIndexRoute
  '/admin/contracts_/new': typeof AdminContractsNewRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/emails/$emailDesignId': typeof AdminEmailsEmailDesignIdRoute
  '/admin/events/$eventTemplateId': typeof AdminEventsEventTemplateIdRoute
  '/admin/events/scheduled': typeof AdminEventsScheduledRoute
  '/admin/events/settings': typeof AdminEventsSettingsRoute
  '/admin/events/templates': typeof AdminEventsTemplatesRoute
  '/admin/learners/$userId': typeof AdminLearnersUserIdRoute
  '/admin/surveys/$surveyId': typeof AdminSurveysSurveyIdRoute
  '/api/admin/accreditation-logos': typeof ApiAdminAccreditationLogosRoute
  '/api/admin/offering-images': typeof ApiAdminOfferingImagesRouteWithChildren
  '/api/admin/resources': typeof ApiAdminResourcesRoute
  '/api/admin/scorm-packages': typeof ApiAdminScormPackagesRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/livekit/webhook': typeof ApiLivekitWebhookRoute
  '/api/scorm/launch': typeof ApiScormLaunchRoute
  '/api/scorm/launches': typeof ApiScormLaunchesRoute
  '/api/scorm/preview': typeof ApiScormPreviewRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/textbee/webhook': typeof ApiTextbeeWebhookRoute
  '/courses/$slug_/bulk-order': typeof CoursesSlugBulkOrderRoute
  '/events/$slug_/bulk-order': typeof EventsSlugBulkOrderRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/emails/': typeof AdminEmailsIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/learners/': typeof AdminLearnersIndexRoute
  '/admin/surveys/': typeof AdminSurveysIndexRoute
  '/admin/events/instances/$eventOccurrenceId': typeof AdminEventsInstancesEventOccurrenceIdRoute
  '/admin/events/instances_/new': typeof AdminEventsInstancesNewRoute
  '/api/access-management/$accessGrantId/codes.csv': typeof ApiAccessManagementAccessGrantIdCodesDotcsvRoute
  '/api/access-management/$accessGrantId/learners.csv': typeof ApiAccessManagementAccessGrantIdLearnersDotcsvRoute
  '/api/admin/offering-images/$assetId': typeof ApiAdminOfferingImagesAssetIdRoute
  '/api/event-operations/$eventOccurrenceId/progress.csv': typeof ApiEventOperationsEventOccurrenceIdProgressDotcsvRoute
  '/api/event-surveys/$publicReference/qr.svg': typeof ApiEventSurveysPublicReferenceQrDotsvgRoute
  '/api/learning/certificates/$enrollmentId': typeof ApiLearningCertificatesEnrollmentIdRoute
  '/api/learning/event-certificates/$eventParticipationId': typeof ApiLearningEventCertificatesEventParticipationIdRoute
  '/api/learning/resources/$resourceVersionId': typeof ApiLearningResourcesResourceVersionIdRoute
  '/api/scorm/attempts/$attemptId': typeof ApiScormAttemptsAttemptIdRouteWithChildren
  '/api/scorm/previews/$packageVersionId': typeof ApiScormPreviewsPackageVersionIdRouteWithChildren
  '/event-operations/$eventOccurrenceId_/survey-qr/$eventSurveyAccessId': typeof EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRoute
  '/learn/$enrollmentId_/surveys/$courseVersionItemId': typeof LearnEnrollmentIdSurveysCourseVersionItemIdRoute
  '/my-events_/$eventOccurrenceId_/surveys/$eventTemplateVersionItemId': typeof MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRoute
  '/admin/learners/$userId_/enrollments/$enrollmentId': typeof AdminLearnersUserIdEnrollmentsEnrollmentIdRoute
  '/admin/learners/$userId_/events/$eventOccurrenceId': typeof AdminLearnersUserIdEventsEventOccurrenceIdRoute
  '/api/access-management/contracts/$enterpriseContractId/utilisation.csv': typeof ApiAccessManagementContractsEnterpriseContractIdUtilisationDotcsvRoute
  '/api/admin/contracts/$enterpriseContractId/utilisation.csv': typeof ApiAdminContractsEnterpriseContractIdUtilisationDotcsvRoute
  '/api/admin/scorm-packages/$packageVersionId/preview': typeof ApiAdminScormPackagesPackageVersionIdPreviewRoute
  '/api/catalog/courses/$slug/accreditation-logos/$assetId': typeof ApiCatalogCoursesSlugAccreditationLogosAssetIdRoute
  '/api/catalog/courses/$slug/cover-images/$assetId': typeof ApiCatalogCoursesSlugCoverImagesAssetIdRoute
  '/api/catalog/events/$slug/accreditation-logos/$assetId': typeof ApiCatalogEventsSlugAccreditationLogosAssetIdRoute
  '/api/catalog/events/$slug/cover-images/$assetId': typeof ApiCatalogEventsSlugCoverImagesAssetIdRoute
  '/api/scorm/attempts/$attemptId/content/$': typeof ApiScormAttemptsAttemptIdContentSplatRoute
  '/api/scorm/previews/$packageVersionId/content/$': typeof ApiScormPreviewsPackageVersionIdContentSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-management'
    | '/admin'
    | '/dashboard'
    | '/event-invitation'
    | '/event-operations'
    | '/login'
    | '/my-events'
    | '/onboarding'
    | '/profile'
    | '/account/setup'
    | '/admin/access'
    | '/admin/administrators'
    | '/admin/contracts'
    | '/admin/modules'
    | '/admin/notifications'
    | '/admin/onboarding'
    | '/admin/resources'
    | '/api/health'
    | '/checkout/success'
    | '/courses/$slug'
    | '/event-access/$publicReference'
    | '/event-operations/$eventOccurrenceId'
    | '/event-surveys/$publicReference'
    | '/events/$slug'
    | '/learn/$enrollmentId'
    | '/my-events/$eventOccurrenceId'
    | '/admin/'
    | '/courses/'
    | '/event-operations/'
    | '/admin/contracts/new'
    | '/admin/courses/$courseId'
    | '/admin/emails/$emailDesignId'
    | '/admin/events/$eventTemplateId'
    | '/admin/events/scheduled'
    | '/admin/events/settings'
    | '/admin/events/templates'
    | '/admin/learners/$userId'
    | '/admin/surveys/$surveyId'
    | '/api/admin/accreditation-logos'
    | '/api/admin/offering-images'
    | '/api/admin/resources'
    | '/api/admin/scorm-packages'
    | '/api/auth/$'
    | '/api/livekit/webhook'
    | '/api/scorm/launch'
    | '/api/scorm/launches'
    | '/api/scorm/preview'
    | '/api/stripe/webhook'
    | '/api/textbee/webhook'
    | '/courses/$slug/bulk-order'
    | '/events/$slug/bulk-order'
    | '/admin/courses/'
    | '/admin/emails/'
    | '/admin/events/'
    | '/admin/learners/'
    | '/admin/surveys/'
    | '/admin/events/instances/$eventOccurrenceId'
    | '/admin/events/instances/new'
    | '/api/access-management/$accessGrantId/codes.csv'
    | '/api/access-management/$accessGrantId/learners.csv'
    | '/api/admin/offering-images/$assetId'
    | '/api/event-operations/$eventOccurrenceId/progress.csv'
    | '/api/event-surveys/$publicReference/qr.svg'
    | '/api/learning/certificates/$enrollmentId'
    | '/api/learning/event-certificates/$eventParticipationId'
    | '/api/learning/resources/$resourceVersionId'
    | '/api/scorm/attempts/$attemptId'
    | '/api/scorm/previews/$packageVersionId'
    | '/event-operations/$eventOccurrenceId/survey-qr/$eventSurveyAccessId'
    | '/learn/$enrollmentId/surveys/$courseVersionItemId'
    | '/my-events/$eventOccurrenceId/surveys/$eventTemplateVersionItemId'
    | '/admin/learners/$userId/enrollments/$enrollmentId'
    | '/admin/learners/$userId/events/$eventOccurrenceId'
    | '/api/access-management/contracts/$enterpriseContractId/utilisation.csv'
    | '/api/admin/contracts/$enterpriseContractId/utilisation.csv'
    | '/api/admin/scorm-packages/$packageVersionId/preview'
    | '/api/catalog/courses/$slug/accreditation-logos/$assetId'
    | '/api/catalog/courses/$slug/cover-images/$assetId'
    | '/api/catalog/events/$slug/accreditation-logos/$assetId'
    | '/api/catalog/events/$slug/cover-images/$assetId'
    | '/api/scorm/attempts/$attemptId/content/$'
    | '/api/scorm/previews/$packageVersionId/content/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-management'
    | '/dashboard'
    | '/event-invitation'
    | '/login'
    | '/my-events'
    | '/onboarding'
    | '/profile'
    | '/account/setup'
    | '/admin/access'
    | '/admin/administrators'
    | '/admin/contracts'
    | '/admin/modules'
    | '/admin/notifications'
    | '/admin/onboarding'
    | '/admin/resources'
    | '/api/health'
    | '/checkout/success'
    | '/courses/$slug'
    | '/event-access/$publicReference'
    | '/event-operations/$eventOccurrenceId'
    | '/event-surveys/$publicReference'
    | '/events/$slug'
    | '/learn/$enrollmentId'
    | '/my-events/$eventOccurrenceId'
    | '/admin'
    | '/courses'
    | '/event-operations'
    | '/admin/contracts/new'
    | '/admin/courses/$courseId'
    | '/admin/emails/$emailDesignId'
    | '/admin/events/$eventTemplateId'
    | '/admin/events/scheduled'
    | '/admin/events/settings'
    | '/admin/events/templates'
    | '/admin/learners/$userId'
    | '/admin/surveys/$surveyId'
    | '/api/admin/accreditation-logos'
    | '/api/admin/offering-images'
    | '/api/admin/resources'
    | '/api/admin/scorm-packages'
    | '/api/auth/$'
    | '/api/livekit/webhook'
    | '/api/scorm/launch'
    | '/api/scorm/launches'
    | '/api/scorm/preview'
    | '/api/stripe/webhook'
    | '/api/textbee/webhook'
    | '/courses/$slug/bulk-order'
    | '/events/$slug/bulk-order'
    | '/admin/courses'
    | '/admin/emails'
    | '/admin/events'
    | '/admin/learners'
    | '/admin/surveys'
    | '/admin/events/instances/$eventOccurrenceId'
    | '/admin/events/instances/new'
    | '/api/access-management/$accessGrantId/codes.csv'
    | '/api/access-management/$accessGrantId/learners.csv'
    | '/api/admin/offering-images/$assetId'
    | '/api/event-operations/$eventOccurrenceId/progress.csv'
    | '/api/event-surveys/$publicReference/qr.svg'
    | '/api/learning/certificates/$enrollmentId'
    | '/api/learning/event-certificates/$eventParticipationId'
    | '/api/learning/resources/$resourceVersionId'
    | '/api/scorm/attempts/$attemptId'
    | '/api/scorm/previews/$packageVersionId'
    | '/event-operations/$eventOccurrenceId/survey-qr/$eventSurveyAccessId'
    | '/learn/$enrollmentId/surveys/$courseVersionItemId'
    | '/my-events/$eventOccurrenceId/surveys/$eventTemplateVersionItemId'
    | '/admin/learners/$userId/enrollments/$enrollmentId'
    | '/admin/learners/$userId/events/$eventOccurrenceId'
    | '/api/access-management/contracts/$enterpriseContractId/utilisation.csv'
    | '/api/admin/contracts/$enterpriseContractId/utilisation.csv'
    | '/api/admin/scorm-packages/$packageVersionId/preview'
    | '/api/catalog/courses/$slug/accreditation-logos/$assetId'
    | '/api/catalog/courses/$slug/cover-images/$assetId'
    | '/api/catalog/events/$slug/accreditation-logos/$assetId'
    | '/api/catalog/events/$slug/cover-images/$assetId'
    | '/api/scorm/attempts/$attemptId/content/$'
    | '/api/scorm/previews/$packageVersionId/content/$'
  id:
    | '__root__'
    | '/'
    | '/access-management'
    | '/admin'
    | '/dashboard'
    | '/event-invitation'
    | '/event-operations'
    | '/login'
    | '/my-events'
    | '/onboarding'
    | '/profile'
    | '/account/setup'
    | '/admin/access'
    | '/admin/administrators'
    | '/admin/contracts'
    | '/admin/modules'
    | '/admin/notifications'
    | '/admin/onboarding'
    | '/admin/resources'
    | '/api/health'
    | '/checkout/success'
    | '/courses/$slug'
    | '/event-access/$publicReference'
    | '/event-operations/$eventOccurrenceId'
    | '/event-surveys/$publicReference'
    | '/events/$slug'
    | '/learn/$enrollmentId'
    | '/my-events_/$eventOccurrenceId'
    | '/admin/'
    | '/courses/'
    | '/event-operations/'
    | '/admin/contracts_/new'
    | '/admin/courses/$courseId'
    | '/admin/emails/$emailDesignId'
    | '/admin/events/$eventTemplateId'
    | '/admin/events/scheduled'
    | '/admin/events/settings'
    | '/admin/events/templates'
    | '/admin/learners/$userId'
    | '/admin/surveys/$surveyId'
    | '/api/admin/accreditation-logos'
    | '/api/admin/offering-images'
    | '/api/admin/resources'
    | '/api/admin/scorm-packages'
    | '/api/auth/$'
    | '/api/livekit/webhook'
    | '/api/scorm/launch'
    | '/api/scorm/launches'
    | '/api/scorm/preview'
    | '/api/stripe/webhook'
    | '/api/textbee/webhook'
    | '/courses/$slug_/bulk-order'
    | '/events/$slug_/bulk-order'
    | '/admin/courses/'
    | '/admin/emails/'
    | '/admin/events/'
    | '/admin/learners/'
    | '/admin/surveys/'
    | '/admin/events/instances/$eventOccurrenceId'
    | '/admin/events/instances_/new'
    | '/api/access-management/$accessGrantId/codes.csv'
    | '/api/access-management/$accessGrantId/learners.csv'
    | '/api/admin/offering-images/$assetId'
    | '/api/event-operations/$eventOccurrenceId/progress.csv'
    | '/api/event-surveys/$publicReference/qr.svg'
    | '/api/learning/certificates/$enrollmentId'
    | '/api/learning/event-certificates/$eventParticipationId'
    | '/api/learning/resources/$resourceVersionId'
    | '/api/scorm/attempts/$attemptId'
    | '/api/scorm/previews/$packageVersionId'
    | '/event-operations/$eventOccurrenceId_/survey-qr/$eventSurveyAccessId'
    | '/learn/$enrollmentId_/surveys/$courseVersionItemId'
    | '/my-events_/$eventOccurrenceId_/surveys/$eventTemplateVersionItemId'
    | '/admin/learners/$userId_/enrollments/$enrollmentId'
    | '/admin/learners/$userId_/events/$eventOccurrenceId'
    | '/api/access-management/contracts/$enterpriseContractId/utilisation.csv'
    | '/api/admin/contracts/$enterpriseContractId/utilisation.csv'
    | '/api/admin/scorm-packages/$packageVersionId/preview'
    | '/api/catalog/courses/$slug/accreditation-logos/$assetId'
    | '/api/catalog/courses/$slug/cover-images/$assetId'
    | '/api/catalog/events/$slug/accreditation-logos/$assetId'
    | '/api/catalog/events/$slug/cover-images/$assetId'
    | '/api/scorm/attempts/$attemptId/content/$'
    | '/api/scorm/previews/$packageVersionId/content/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessManagementRoute: typeof AccessManagementRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  EventInvitationRoute: typeof EventInvitationRoute
  EventOperationsRoute: typeof EventOperationsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MyEventsRoute: typeof MyEventsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  AccountSetupRoute: typeof AccountSetupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  EventAccessPublicReferenceRoute: typeof EventAccessPublicReferenceRoute
  EventSurveysPublicReferenceRoute: typeof EventSurveysPublicReferenceRoute
  EventsSlugRoute: typeof EventsSlugRoute
  LearnEnrollmentIdRoute: typeof LearnEnrollmentIdRoute
  MyEventsEventOccurrenceIdRoute: typeof MyEventsEventOccurrenceIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ApiAdminAccreditationLogosRoute: typeof ApiAdminAccreditationLogosRoute
  ApiAdminOfferingImagesRoute: typeof ApiAdminOfferingImagesRouteWithChildren
  ApiAdminResourcesRoute: typeof ApiAdminResourcesRoute
  ApiAdminScormPackagesRoute: typeof ApiAdminScormPackagesRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiLivekitWebhookRoute: typeof ApiLivekitWebhookRoute
  ApiScormLaunchRoute: typeof ApiScormLaunchRoute
  ApiScormLaunchesRoute: typeof ApiScormLaunchesRoute
  ApiScormPreviewRoute: typeof ApiScormPreviewRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiTextbeeWebhookRoute: typeof ApiTextbeeWebhookRoute
  CoursesSlugBulkOrderRoute: typeof CoursesSlugBulkOrderRoute
  EventsSlugBulkOrderRoute: typeof EventsSlugBulkOrderRoute
  ApiAccessManagementAccessGrantIdCodesDotcsvRoute: typeof ApiAccessManagementAccessGrantIdCodesDotcsvRoute
  ApiAccessManagementAccessGrantIdLearnersDotcsvRoute: typeof ApiAccessManagementAccessGrantIdLearnersDotcsvRoute
  ApiEventOperationsEventOccurrenceIdProgressDotcsvRoute: typeof ApiEventOperationsEventOccurrenceIdProgressDotcsvRoute
  ApiEventSurveysPublicReferenceQrDotsvgRoute: typeof ApiEventSurveysPublicReferenceQrDotsvgRoute
  ApiLearningCertificatesEnrollmentIdRoute: typeof ApiLearningCertificatesEnrollmentIdRoute
  ApiLearningEventCertificatesEventParticipationIdRoute: typeof ApiLearningEventCertificatesEventParticipationIdRoute
  ApiLearningResourcesResourceVersionIdRoute: typeof ApiLearningResourcesResourceVersionIdRoute
  ApiScormAttemptsAttemptIdRoute: typeof ApiScormAttemptsAttemptIdRouteWithChildren
  ApiScormPreviewsPackageVersionIdRoute: typeof ApiScormPreviewsPackageVersionIdRouteWithChildren
  LearnEnrollmentIdSurveysCourseVersionItemIdRoute: typeof LearnEnrollmentIdSurveysCourseVersionItemIdRoute
  MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRoute: typeof MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRoute
  ApiAccessManagementContractsEnterpriseContractIdUtilisationDotcsvRoute: typeof ApiAccessManagementContractsEnterpriseContractIdUtilisationDotcsvRoute
  ApiAdminContractsEnterpriseContractIdUtilisationDotcsvRoute: typeof ApiAdminContractsEnterpriseContractIdUtilisationDotcsvRoute
  ApiCatalogCoursesSlugAccreditationLogosAssetIdRoute: typeof ApiCatalogCoursesSlugAccreditationLogosAssetIdRoute
  ApiCatalogCoursesSlugCoverImagesAssetIdRoute: typeof ApiCatalogCoursesSlugCoverImagesAssetIdRoute
  ApiCatalogEventsSlugAccreditationLogosAssetIdRoute: typeof ApiCatalogEventsSlugAccreditationLogosAssetIdRoute
  ApiCatalogEventsSlugCoverImagesAssetIdRoute: typeof ApiCatalogEventsSlugCoverImagesAssetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-management': {
      id: '/access-management'
      path: '/access-management'
      fullPath: '/access-management'
      preLoaderRoute: typeof AccessManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-invitation': {
      id: '/event-invitation'
      path: '/event-invitation'
      fullPath: '/event-invitation'
      preLoaderRoute: typeof EventInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-operations': {
      id: '/event-operations'
      path: '/event-operations'
      fullPath: '/event-operations'
      preLoaderRoute: typeof EventOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/setup': {
      id: '/account/setup'
      path: '/account/setup'
      fullPath: '/account/setup'
      preLoaderRoute: typeof AccountSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administrators': {
      id: '/admin/administrators'
      path: '/administrators'
      fullPath: '/admin/administrators'
      preLoaderRoute: typeof AdminAdministratorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contracts': {
      id: '/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AdminContractsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modules': {
      id: '/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/onboarding': {
      id: '/admin/onboarding'
      path: '/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AdminOnboardingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-access/$publicReference': {
      id: '/event-access/$publicReference'
      path: '/event-access/$publicReference'
      fullPath: '/event-access/$publicReference'
      preLoaderRoute: typeof EventAccessPublicReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-operations/': {
      id: '/event-operations/'
      path: '/'
      fullPath: '/event-operations/'
      preLoaderRoute: typeof EventOperationsIndexRouteImport
      parentRoute: typeof EventOperationsRoute
    }
    '/event-operations/$eventOccurrenceId': {
      id: '/event-operations/$eventOccurrenceId'
      path: '/$eventOccurrenceId'
      fullPath: '/event-operations/$eventOccurrenceId'
      preLoaderRoute: typeof EventOperationsEventOccurrenceIdRouteImport
      parentRoute: typeof EventOperationsRoute
    }
    '/event-surveys/$publicReference': {
      id: '/event-surveys/$publicReference'
      path: '/event-surveys/$publicReference'
      fullPath: '/event-surveys/$publicReference'
      preLoaderRoute: typeof EventSurveysPublicReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$enrollmentId': {
      id: '/learn/$enrollmentId'
      path: '/learn/$enrollmentId'
      fullPath: '/learn/$enrollmentId'
      preLoaderRoute: typeof LearnEnrollmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events_/$eventOccurrenceId': {
      id: '/my-events_/$eventOccurrenceId'
      path: '/my-events/$eventOccurrenceId'
      fullPath: '/my-events/$eventOccurrenceId'
      preLoaderRoute: typeof MyEventsEventOccurrenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contracts_/new': {
      id: '/admin/contracts_/new'
      path: '/contracts/new'
      fullPath: '/admin/contracts/new'
      preLoaderRoute: typeof AdminContractsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/$courseId': {
      id: '/admin/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AdminCoursesCourseIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails/': {
      id: '/admin/emails/'
      path: '/emails'
      fullPath: '/admin/emails/'
      preLoaderRoute: typeof AdminEmailsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails/$emailDesignId': {
      id: '/admin/emails/$emailDesignId'
      path: '/emails/$emailDesignId'
      fullPath: '/admin/emails/$emailDesignId'
      preLoaderRoute: typeof AdminEmailsEmailDesignIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$eventTemplateId': {
      id: '/admin/events/$eventTemplateId'
      path: '/events/$eventTemplateId'
      fullPath: '/admin/events/$eventTemplateId'
      preLoaderRoute: typeof AdminEventsEventTemplateIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/scheduled': {
      id: '/admin/events/scheduled'
      path: '/events/scheduled'
      fullPath: '/admin/events/scheduled'
      preLoaderRoute: typeof AdminEventsScheduledRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/settings': {
      id: '/admin/events/settings'
      path: '/events/settings'
      fullPath: '/admin/events/settings'
      preLoaderRoute: typeof AdminEventsSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/templates': {
      id: '/admin/events/templates'
      path: '/events/templates'
      fullPath: '/admin/events/templates'
      preLoaderRoute: typeof AdminEventsTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/learners/': {
      id: '/admin/learners/'
      path: '/learners'
      fullPath: '/admin/learners/'
      preLoaderRoute: typeof AdminLearnersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/learners/$userId': {
      id: '/admin/learners/$userId'
      path: '/learners/$userId'
      fullPath: '/admin/learners/$userId'
      preLoaderRoute: typeof AdminLearnersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/surveys/': {
      id: '/admin/surveys/'
      path: '/surveys'
      fullPath: '/admin/surveys/'
      preLoaderRoute: typeof AdminSurveysIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/surveys/$surveyId': {
      id: '/admin/surveys/$surveyId'
      path: '/surveys/$surveyId'
      fullPath: '/admin/surveys/$surveyId'
      preLoaderRoute: typeof AdminSurveysSurveyIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/accreditation-logos': {
      id: '/api/admin/accreditation-logos'
      path: '/api/admin/accreditation-logos'
      fullPath: '/api/admin/accreditation-logos'
      preLoaderRoute: typeof ApiAdminAccreditationLogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/offering-images': {
      id: '/api/admin/offering-images'
      path: '/api/admin/offering-images'
      fullPath: '/api/admin/offering-images'
      preLoaderRoute: typeof ApiAdminOfferingImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/resources': {
      id: '/api/admin/resources'
      path: '/api/admin/resources'
      fullPath: '/api/admin/resources'
      preLoaderRoute: typeof ApiAdminResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/scorm-packages': {
      id: '/api/admin/scorm-packages'
      path: '/api/admin/scorm-packages'
      fullPath: '/api/admin/scorm-packages'
      preLoaderRoute: typeof ApiAdminScormPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/livekit/webhook': {
      id: '/api/livekit/webhook'
      path: '/api/livekit/webhook'
      fullPath: '/api/livekit/webhook'
      preLoaderRoute: typeof ApiLivekitWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scorm/launch': {
      id: '/api/scorm/launch'
      path: '/api/scorm/launch'
      fullPath: '/api/scorm/launch'
      preLoaderRoute: typeof ApiScormLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scorm/launches': {
      id: '/api/scorm/launches'
      path: '/api/scorm/launches'
      fullPath: '/api/scorm/launches'
      preLoaderRoute: typeof ApiScormLaunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scorm/preview': {
      id: '/api/scorm/preview'
      path: '/api/scorm/preview'
      fullPath: '/api/scorm/preview'
      preLoaderRoute: typeof ApiScormPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/textbee/webhook': {
      id: '/api/textbee/webhook'
      path: '/api/textbee/webhook'
      fullPath: '/api/textbee/webhook'
      preLoaderRoute: typeof ApiTextbeeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug_/bulk-order': {
      id: '/courses/$slug_/bulk-order'
      path: '/courses/$slug/bulk-order'
      fullPath: '/courses/$slug/bulk-order'
      preLoaderRoute: typeof CoursesSlugBulkOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug_/bulk-order': {
      id: '/events/$slug_/bulk-order'
      path: '/events/$slug/bulk-order'
      fullPath: '/events/$slug/bulk-order'
      preLoaderRoute: typeof EventsSlugBulkOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/instances/$eventOccurrenceId': {
      id: '/admin/events/instances/$eventOccurrenceId'
      path: '/events/instances/$eventOccurrenceId'
      fullPath: '/admin/events/instances/$eventOccurrenceId'
      preLoaderRoute: typeof AdminEventsInstancesEventOccurrenceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/instances_/new': {
      id: '/admin/events/instances_/new'
      path: '/events/instances/new'
      fullPath: '/admin/events/instances/new'
      preLoaderRoute: typeof AdminEventsInstancesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/access-management/$accessGrantId/codes.csv': {
      id: '/api/access-management/$accessGrantId/codes.csv'
      path: '/api/access-management/$accessGrantId/codes.csv'
      fullPath: '/api/access-management/$accessGrantId/codes.csv'
      preLoaderRoute: typeof ApiAccessManagementAccessGrantIdCodesDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/access-management/$accessGrantId/learners.csv': {
      id: '/api/access-management/$accessGrantId/learners.csv'
      path: '/api/access-management/$accessGrantId/learners.csv'
      fullPath: '/api/access-management/$accessGrantId/learners.csv'
      preLoaderRoute: typeof ApiAccessManagementAccessGrantIdLearnersDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/offering-images/$assetId': {
      id: '/api/admin/offering-images/$assetId'
      path: '/$assetId'
      fullPath: '/api/admin/offering-images/$assetId'
      preLoaderRoute: typeof ApiAdminOfferingImagesAssetIdRouteImport
      parentRoute: typeof ApiAdminOfferingImagesRoute
    }
    '/api/event-operations/$eventOccurrenceId/progress.csv': {
      id: '/api/event-operations/$eventOccurrenceId/progress.csv'
      path: '/api/event-operations/$eventOccurrenceId/progress.csv'
      fullPath: '/api/event-operations/$eventOccurrenceId/progress.csv'
      preLoaderRoute: typeof ApiEventOperationsEventOccurrenceIdProgressDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/event-surveys/$publicReference/qr.svg': {
      id: '/api/event-surveys/$publicReference/qr.svg'
      path: '/api/event-surveys/$publicReference/qr.svg'
      fullPath: '/api/event-surveys/$publicReference/qr.svg'
      preLoaderRoute: typeof ApiEventSurveysPublicReferenceQrDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/certificates/$enrollmentId': {
      id: '/api/learning/certificates/$enrollmentId'
      path: '/api/learning/certificates/$enrollmentId'
      fullPath: '/api/learning/certificates/$enrollmentId'
      preLoaderRoute: typeof ApiLearningCertificatesEnrollmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/event-certificates/$eventParticipationId': {
      id: '/api/learning/event-certificates/$eventParticipationId'
      path: '/api/learning/event-certificates/$eventParticipationId'
      fullPath: '/api/learning/event-certificates/$eventParticipationId'
      preLoaderRoute: typeof ApiLearningEventCertificatesEventParticipationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/resources/$resourceVersionId': {
      id: '/api/learning/resources/$resourceVersionId'
      path: '/api/learning/resources/$resourceVersionId'
      fullPath: '/api/learning/resources/$resourceVersionId'
      preLoaderRoute: typeof ApiLearningResourcesResourceVersionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scorm/attempts/$attemptId': {
      id: '/api/scorm/attempts/$attemptId'
      path: '/api/scorm/attempts/$attemptId'
      fullPath: '/api/scorm/attempts/$attemptId'
      preLoaderRoute: typeof ApiScormAttemptsAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scorm/previews/$packageVersionId': {
      id: '/api/scorm/previews/$packageVersionId'
      path: '/api/scorm/previews/$packageVersionId'
      fullPath: '/api/scorm/previews/$packageVersionId'
      preLoaderRoute: typeof ApiScormPreviewsPackageVersionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-operations/$eventOccurrenceId_/survey-qr/$eventSurveyAccessId': {
      id: '/event-operations/$eventOccurrenceId_/survey-qr/$eventSurveyAccessId'
      path: '/$eventOccurrenceId/survey-qr/$eventSurveyAccessId'
      fullPath: '/event-operations/$eventOccurrenceId/survey-qr/$eventSurveyAccessId'
      preLoaderRoute: typeof EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRouteImport
      parentRoute: typeof EventOperationsRoute
    }
    '/learn/$enrollmentId_/surveys/$courseVersionItemId': {
      id: '/learn/$enrollmentId_/surveys/$courseVersionItemId'
      path: '/learn/$enrollmentId/surveys/$courseVersionItemId'
      fullPath: '/learn/$enrollmentId/surveys/$courseVersionItemId'
      preLoaderRoute: typeof LearnEnrollmentIdSurveysCourseVersionItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events_/$eventOccurrenceId_/surveys/$eventTemplateVersionItemId': {
      id: '/my-events_/$eventOccurrenceId_/surveys/$eventTemplateVersionItemId'
      path: '/my-events/$eventOccurrenceId/surveys/$eventTemplateVersionItemId'
      fullPath: '/my-events/$eventOccurrenceId/surveys/$eventTemplateVersionItemId'
      preLoaderRoute: typeof MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/learners/$userId_/enrollments/$enrollmentId': {
      id: '/admin/learners/$userId_/enrollments/$enrollmentId'
      path: '/learners/$userId/enrollments/$enrollmentId'
      fullPath: '/admin/learners/$userId/enrollments/$enrollmentId'
      preLoaderRoute: typeof AdminLearnersUserIdEnrollmentsEnrollmentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/learners/$userId_/events/$eventOccurrenceId': {
      id: '/admin/learners/$userId_/events/$eventOccurrenceId'
      path: '/learners/$userId/events/$eventOccurrenceId'
      fullPath: '/admin/learners/$userId/events/$eventOccurrenceId'
      preLoaderRoute: typeof AdminLearnersUserIdEventsEventOccurrenceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/access-management/contracts/$enterpriseContractId/utilisation.csv': {
      id: '/api/access-management/contracts/$enterpriseContractId/utilisation.csv'
      path: '/api/access-management/contracts/$enterpriseContractId/utilisation.csv'
      fullPath: '/api/access-management/contracts/$enterpriseContractId/utilisation.csv'
      preLoaderRoute: typeof ApiAccessManagementContractsEnterpriseContractIdUtilisationDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/contracts/$enterpriseContractId/utilisation.csv': {
      id: '/api/admin/contracts/$enterpriseContractId/utilisation.csv'
      path: '/api/admin/contracts/$enterpriseContractId/utilisation.csv'
      fullPath: '/api/admin/contracts/$enterpriseContractId/utilisation.csv'
      preLoaderRoute: typeof ApiAdminContractsEnterpriseContractIdUtilisationDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/scorm-packages/$packageVersionId/preview': {
      id: '/api/admin/scorm-packages/$packageVersionId/preview'
      path: '/$packageVersionId/preview'
      fullPath: '/api/admin/scorm-packages/$packageVersionId/preview'
      preLoaderRoute: typeof ApiAdminScormPackagesPackageVersionIdPreviewRouteImport
      parentRoute: typeof ApiAdminScormPackagesRoute
    }
    '/api/catalog/courses/$slug/accreditation-logos/$assetId': {
      id: '/api/catalog/courses/$slug/accreditation-logos/$assetId'
      path: '/api/catalog/courses/$slug/accreditation-logos/$assetId'
      fullPath: '/api/catalog/courses/$slug/accreditation-logos/$assetId'
      preLoaderRoute: typeof ApiCatalogCoursesSlugAccreditationLogosAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/courses/$slug/cover-images/$assetId': {
      id: '/api/catalog/courses/$slug/cover-images/$assetId'
      path: '/api/catalog/courses/$slug/cover-images/$assetId'
      fullPath: '/api/catalog/courses/$slug/cover-images/$assetId'
      preLoaderRoute: typeof ApiCatalogCoursesSlugCoverImagesAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/events/$slug/accreditation-logos/$assetId': {
      id: '/api/catalog/events/$slug/accreditation-logos/$assetId'
      path: '/api/catalog/events/$slug/accreditation-logos/$assetId'
      fullPath: '/api/catalog/events/$slug/accreditation-logos/$assetId'
      preLoaderRoute: typeof ApiCatalogEventsSlugAccreditationLogosAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/events/$slug/cover-images/$assetId': {
      id: '/api/catalog/events/$slug/cover-images/$assetId'
      path: '/api/catalog/events/$slug/cover-images/$assetId'
      fullPath: '/api/catalog/events/$slug/cover-images/$assetId'
      preLoaderRoute: typeof ApiCatalogEventsSlugCoverImagesAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scorm/attempts/$attemptId/content/$': {
      id: '/api/scorm/attempts/$attemptId/content/$'
      path: '/content/$'
      fullPath: '/api/scorm/attempts/$attemptId/content/$'
      preLoaderRoute: typeof ApiScormAttemptsAttemptIdContentSplatRouteImport
      parentRoute: typeof ApiScormAttemptsAttemptIdRoute
    }
    '/api/scorm/previews/$packageVersionId/content/$': {
      id: '/api/scorm/previews/$packageVersionId/content/$'
      path: '/content/$'
      fullPath: '/api/scorm/previews/$packageVersionId/content/$'
      preLoaderRoute: typeof ApiScormPreviewsPackageVersionIdContentSplatRouteImport
      parentRoute: typeof ApiScormPreviewsPackageVersionIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccessRoute: typeof AdminAccessRoute
  AdminAdministratorsRoute: typeof AdminAdministratorsRoute
  AdminContractsRoute: typeof AdminContractsRoute
  AdminModulesRoute: typeof AdminModulesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOnboardingRoute: typeof AdminOnboardingRoute
  AdminResourcesRoute: typeof AdminResourcesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminContractsNewRoute: typeof AdminContractsNewRoute
  AdminCoursesCourseIdRoute: typeof AdminCoursesCourseIdRoute
  AdminEmailsEmailDesignIdRoute: typeof AdminEmailsEmailDesignIdRoute
  AdminEventsEventTemplateIdRoute: typeof AdminEventsEventTemplateIdRoute
  AdminEventsScheduledRoute: typeof AdminEventsScheduledRoute
  AdminEventsSettingsRoute: typeof AdminEventsSettingsRoute
  AdminEventsTemplatesRoute: typeof AdminEventsTemplatesRoute
  AdminLearnersUserIdRoute: typeof AdminLearnersUserIdRoute
  AdminSurveysSurveyIdRoute: typeof AdminSurveysSurveyIdRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminEmailsIndexRoute: typeof AdminEmailsIndexRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminLearnersIndexRoute: typeof AdminLearnersIndexRoute
  AdminSurveysIndexRoute: typeof AdminSurveysIndexRoute
  AdminEventsInstancesEventOccurrenceIdRoute: typeof AdminEventsInstancesEventOccurrenceIdRoute
  AdminEventsInstancesNewRoute: typeof AdminEventsInstancesNewRoute
  AdminLearnersUserIdEnrollmentsEnrollmentIdRoute: typeof AdminLearnersUserIdEnrollmentsEnrollmentIdRoute
  AdminLearnersUserIdEventsEventOccurrenceIdRoute: typeof AdminLearnersUserIdEventsEventOccurrenceIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessRoute: AdminAccessRoute,
  AdminAdministratorsRoute: AdminAdministratorsRoute,
  AdminContractsRoute: AdminContractsRoute,
  AdminModulesRoute: AdminModulesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOnboardingRoute: AdminOnboardingRoute,
  AdminResourcesRoute: AdminResourcesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminContractsNewRoute: AdminContractsNewRoute,
  AdminCoursesCourseIdRoute: AdminCoursesCourseIdRoute,
  AdminEmailsEmailDesignIdRoute: AdminEmailsEmailDesignIdRoute,
  AdminEventsEventTemplateIdRoute: AdminEventsEventTemplateIdRoute,
  AdminEventsScheduledRoute: AdminEventsScheduledRoute,
  AdminEventsSettingsRoute: AdminEventsSettingsRoute,
  AdminEventsTemplatesRoute: AdminEventsTemplatesRoute,
  AdminLearnersUserIdRoute: AdminLearnersUserIdRoute,
  AdminSurveysSurveyIdRoute: AdminSurveysSurveyIdRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminEmailsIndexRoute: AdminEmailsIndexRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminLearnersIndexRoute: AdminLearnersIndexRoute,
  AdminSurveysIndexRoute: AdminSurveysIndexRoute,
  AdminEventsInstancesEventOccurrenceIdRoute:
    AdminEventsInstancesEventOccurrenceIdRoute,
  AdminEventsInstancesNewRoute: AdminEventsInstancesNewRoute,
  AdminLearnersUserIdEnrollmentsEnrollmentIdRoute:
    AdminLearnersUserIdEnrollmentsEnrollmentIdRoute,
  AdminLearnersUserIdEventsEventOccurrenceIdRoute:
    AdminLearnersUserIdEventsEventOccurrenceIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EventOperationsRouteChildren {
  EventOperationsEventOccurrenceIdRoute: typeof EventOperationsEventOccurrenceIdRoute
  EventOperationsIndexRoute: typeof EventOperationsIndexRoute
  EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRoute: typeof EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRoute
}

const EventOperationsRouteChildren: EventOperationsRouteChildren = {
  EventOperationsEventOccurrenceIdRoute: EventOperationsEventOccurrenceIdRoute,
  EventOperationsIndexRoute: EventOperationsIndexRoute,
  EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRoute:
    EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRoute,
}

const EventOperationsRouteWithChildren = EventOperationsRoute._addFileChildren(
  EventOperationsRouteChildren,
)

interface ApiAdminOfferingImagesRouteChildren {
  ApiAdminOfferingImagesAssetIdRoute: typeof ApiAdminOfferingImagesAssetIdRoute
}

const ApiAdminOfferingImagesRouteChildren: ApiAdminOfferingImagesRouteChildren =
  {
    ApiAdminOfferingImagesAssetIdRoute: ApiAdminOfferingImagesAssetIdRoute,
  }

const ApiAdminOfferingImagesRouteWithChildren =
  ApiAdminOfferingImagesRoute._addFileChildren(
    ApiAdminOfferingImagesRouteChildren,
  )

interface ApiAdminScormPackagesRouteChildren {
  ApiAdminScormPackagesPackageVersionIdPreviewRoute: typeof ApiAdminScormPackagesPackageVersionIdPreviewRoute
}

const ApiAdminScormPackagesRouteChildren: ApiAdminScormPackagesRouteChildren = {
  ApiAdminScormPackagesPackageVersionIdPreviewRoute:
    ApiAdminScormPackagesPackageVersionIdPreviewRoute,
}

const ApiAdminScormPackagesRouteWithChildren =
  ApiAdminScormPackagesRoute._addFileChildren(
    ApiAdminScormPackagesRouteChildren,
  )

interface ApiScormAttemptsAttemptIdRouteChildren {
  ApiScormAttemptsAttemptIdContentSplatRoute: typeof ApiScormAttemptsAttemptIdContentSplatRoute
}

const ApiScormAttemptsAttemptIdRouteChildren: ApiScormAttemptsAttemptIdRouteChildren =
  {
    ApiScormAttemptsAttemptIdContentSplatRoute:
      ApiScormAttemptsAttemptIdContentSplatRoute,
  }

const ApiScormAttemptsAttemptIdRouteWithChildren =
  ApiScormAttemptsAttemptIdRoute._addFileChildren(
    ApiScormAttemptsAttemptIdRouteChildren,
  )

interface ApiScormPreviewsPackageVersionIdRouteChildren {
  ApiScormPreviewsPackageVersionIdContentSplatRoute: typeof ApiScormPreviewsPackageVersionIdContentSplatRoute
}

const ApiScormPreviewsPackageVersionIdRouteChildren: ApiScormPreviewsPackageVersionIdRouteChildren =
  {
    ApiScormPreviewsPackageVersionIdContentSplatRoute:
      ApiScormPreviewsPackageVersionIdContentSplatRoute,
  }

const ApiScormPreviewsPackageVersionIdRouteWithChildren =
  ApiScormPreviewsPackageVersionIdRoute._addFileChildren(
    ApiScormPreviewsPackageVersionIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessManagementRoute: AccessManagementRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  EventInvitationRoute: EventInvitationRoute,
  EventOperationsRoute: EventOperationsRouteWithChildren,
  LoginRoute: LoginRoute,
  MyEventsRoute: MyEventsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  AccountSetupRoute: AccountSetupRoute,
  ApiHealthRoute: ApiHealthRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  EventAccessPublicReferenceRoute: EventAccessPublicReferenceRoute,
  EventSurveysPublicReferenceRoute: EventSurveysPublicReferenceRoute,
  EventsSlugRoute: EventsSlugRoute,
  LearnEnrollmentIdRoute: LearnEnrollmentIdRoute,
  MyEventsEventOccurrenceIdRoute: MyEventsEventOccurrenceIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ApiAdminAccreditationLogosRoute: ApiAdminAccreditationLogosRoute,
  ApiAdminOfferingImagesRoute: ApiAdminOfferingImagesRouteWithChildren,
  ApiAdminResourcesRoute: ApiAdminResourcesRoute,
  ApiAdminScormPackagesRoute: ApiAdminScormPackagesRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiLivekitWebhookRoute: ApiLivekitWebhookRoute,
  ApiScormLaunchRoute: ApiScormLaunchRoute,
  ApiScormLaunchesRoute: ApiScormLaunchesRoute,
  ApiScormPreviewRoute: ApiScormPreviewRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiTextbeeWebhookRoute: ApiTextbeeWebhookRoute,
  CoursesSlugBulkOrderRoute: CoursesSlugBulkOrderRoute,
  EventsSlugBulkOrderRoute: EventsSlugBulkOrderRoute,
  ApiAccessManagementAccessGrantIdCodesDotcsvRoute:
    ApiAccessManagementAccessGrantIdCodesDotcsvRoute,
  ApiAccessManagementAccessGrantIdLearnersDotcsvRoute:
    ApiAccessManagementAccessGrantIdLearnersDotcsvRoute,
  ApiEventOperationsEventOccurrenceIdProgressDotcsvRoute:
    ApiEventOperationsEventOccurrenceIdProgressDotcsvRoute,
  ApiEventSurveysPublicReferenceQrDotsvgRoute:
    ApiEventSurveysPublicReferenceQrDotsvgRoute,
  ApiLearningCertificatesEnrollmentIdRoute:
    ApiLearningCertificatesEnrollmentIdRoute,
  ApiLearningEventCertificatesEventParticipationIdRoute:
    ApiLearningEventCertificatesEventParticipationIdRoute,
  ApiLearningResourcesResourceVersionIdRoute:
    ApiLearningResourcesResourceVersionIdRoute,
  ApiScormAttemptsAttemptIdRoute: ApiScormAttemptsAttemptIdRouteWithChildren,
  ApiScormPreviewsPackageVersionIdRoute:
    ApiScormPreviewsPackageVersionIdRouteWithChildren,
  LearnEnrollmentIdSurveysCourseVersionItemIdRoute:
    LearnEnrollmentIdSurveysCourseVersionItemIdRoute,
  MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRoute:
    MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRoute,
  ApiAccessManagementContractsEnterpriseContractIdUtilisationDotcsvRoute:
    ApiAccessManagementContractsEnterpriseContractIdUtilisationDotcsvRoute,
  ApiAdminContractsEnterpriseContractIdUtilisationDotcsvRoute:
    ApiAdminContractsEnterpriseContractIdUtilisationDotcsvRoute,
  ApiCatalogCoursesSlugAccreditationLogosAssetIdRoute:
    ApiCatalogCoursesSlugAccreditationLogosAssetIdRoute,
  ApiCatalogCoursesSlugCoverImagesAssetIdRoute:
    ApiCatalogCoursesSlugCoverImagesAssetIdRoute,
  ApiCatalogEventsSlugAccreditationLogosAssetIdRoute:
    ApiCatalogEventsSlugAccreditationLogosAssetIdRoute,
  ApiCatalogEventsSlugCoverImagesAssetIdRoute:
    ApiCatalogEventsSlugCoverImagesAssetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
