/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EventOperationsRouteImport } from './routes/event-operations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AccountSetupRouteImport } from './routes/account.setup'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAccessRouteImport } from './routes/admin.access'
import { Route as AdminModulesRouteImport } from './routes/admin.modules'
import { Route as AdminOnboardingRouteImport } from './routes/admin.onboarding'
import { Route as AdminResourcesRouteImport } from './routes/admin.resources'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as EventOperationsIndexRouteImport } from './routes/event-operations.index'
import { Route as EventOperationsEventOccurrenceIdRouteImport } from './routes/event-operations.$eventOccurrenceId'
import { Route as EventSurveysPublicReferenceRouteImport } from './routes/event-surveys.$publicReference'
import { Route as LearnEnrollmentIdRouteImport } from './routes/learn.$enrollmentId'
import { Route as MyEventsEventOccurrenceIdRouteImport } from './routes/my-events_.$eventOccurrenceId'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin.courses.index'
import { Route as AdminCoursesCourseIdRouteImport } from './routes/admin.courses.$courseId'
import { Route as AdminEventsIndexRouteImport } from './routes/admin.events.index'
import { Route as AdminEventsEventTemplateIdRouteImport } from './routes/admin.events.$eventTemplateId'
import { Route as AdminEventsScheduledRouteImport } from './routes/admin.events.scheduled'
import { Route as AdminEventsSettingsRouteImport } from './routes/admin.events.settings'
import { Route as AdminEventsTemplatesRouteImport } from './routes/admin.events.templates'
import { Route as AdminLearnersIndexRouteImport } from './routes/admin.learners.index'
import { Route as AdminLearnersUserIdRouteImport } from './routes/admin.learners.$userId'
import { Route as AdminSurveysIndexRouteImport } from './routes/admin.surveys.index'
import { Route as AdminSurveysSurveyIdRouteImport } from './routes/admin.surveys.$surveyId'
import { Route as ApiAdminResourcesRouteImport } from './routes/api.admin.resources'
import { Route as ApiAdminScormPackagesRouteImport } from './routes/api.admin.scorm-packages'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiScormLaunchRouteImport } from './routes/api.scorm.launch'
import { Route as ApiScormLaunchesRouteImport } from './routes/api.scorm.launches'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'
import { Route as AdminEventsInstancesEventOccurrenceIdRouteImport } from './routes/admin.events.instances.$eventOccurrenceId'
import { Route as AdminEventsInstancesNewRouteImport } from './routes/admin.events.instances_.new'
import { Route as ApiEventOperationsEventOccurrenceIdProgressDotcsvRouteImport } from './routes/api.event-operations.$eventOccurrenceId.progress[.]csv'
import { Route as ApiEventSurveysPublicReferenceQrDotsvgRouteImport } from './routes/api.event-surveys.$publicReference.qr[.]svg'
import { Route as ApiLearningCertificatesEnrollmentIdRouteImport } from './routes/api.learning.certificates.$enrollmentId'
import { Route as ApiLearningEventCertificatesEventParticipationIdRouteImport } from './routes/api.learning.event-certificates.$eventParticipationId'
import { Route as ApiLearningResourcesResourceVersionIdRouteImport } from './routes/api.learning.resources.$resourceVersionId'
import { Route as ApiScormAttemptsAttemptIdRouteImport } from './routes/api.scorm.attempts.$attemptId'
import { Route as EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRouteImport } from './routes/event-operations.$eventOccurrenceId_.survey-qr.$eventSurveyAccessId'
import { Route as LearnEnrollmentIdSurveysCourseVersionItemIdRouteImport } from './routes/learn.$enrollmentId_.surveys.$courseVersionItemId'
import { Route as MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRouteImport } from './routes/my-events_.$eventOccurrenceId_.surveys.$eventTemplateVersionItemId'
import { Route as AdminLearnersUserIdEnrollmentsEnrollmentIdRouteImport } from './routes/admin.learners.$userId_.enrollments.$enrollmentId'
import { Route as ApiScormAttemptsAttemptIdContentSplatRouteImport } from './routes/api.scorm.attempts.$attemptId.content.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EventOperationsRoute = EventOperationsRouteImport.update({
  id: '/event-operations',
  path: '/event-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSetupRoute = AccountSetupRouteImport.update({
  id: '/account/setup',
  path: '/account/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnboardingRoute = AdminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AdminRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventOperationsIndexRoute = EventOperationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventOperationsRoute,
} as any)
const EventOperationsEventOccurrenceIdRoute =
  EventOperationsEventOccurrenceIdRouteImport.update({
    id: '/$eventOccurrenceId',
    path: '/$eventOccurrenceId',
    getParentRoute: () => EventOperationsRoute,
  } as any)
const EventSurveysPublicReferenceRoute =
  EventSurveysPublicReferenceRouteImport.update({
    id: '/event-surveys/$publicReference',
    path: '/event-surveys/$publicReference',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnEnrollmentIdRoute = LearnEnrollmentIdRouteImport.update({
  id: '/learn/$enrollmentId',
  path: '/learn/$enrollmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsEventOccurrenceIdRoute =
  MyEventsEventOccurrenceIdRouteImport.update({
    id: '/my-events_/$eventOccurrenceId',
    path: '/my-events/$eventOccurrenceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesCourseIdRoute = AdminCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsEventTemplateIdRoute =
  AdminEventsEventTemplateIdRouteImport.update({
    id: '/events/$eventTemplateId',
    path: '/events/$eventTemplateId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEventsScheduledRoute = AdminEventsScheduledRouteImport.update({
  id: '/events/scheduled',
  path: '/events/scheduled',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsSettingsRoute = AdminEventsSettingsRouteImport.update({
  id: '/events/settings',
  path: '/events/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsTemplatesRoute = AdminEventsTemplatesRouteImport.update({
  id: '/events/templates',
  path: '/events/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLearnersIndexRoute = AdminLearnersIndexRouteImport.update({
  id: '/learners/',
  path: '/learners/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLearnersUserIdRoute = AdminLearnersUserIdRouteImport.update({
  id: '/learners/$userId',
  path: '/learners/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSurveysIndexRoute = AdminSurveysIndexRouteImport.update({
  id: '/surveys/',
  path: '/surveys/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSurveysSurveyIdRoute = AdminSurveysSurveyIdRouteImport.update({
  id: '/surveys/$surveyId',
  path: '/surveys/$surveyId',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminResourcesRoute = ApiAdminResourcesRouteImport.update({
  id: '/api/admin/resources',
  path: '/api/admin/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminScormPackagesRoute = ApiAdminScormPackagesRouteImport.update({
  id: '/api/admin/scorm-packages',
  path: '/api/admin/scorm-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScormLaunchRoute = ApiScormLaunchRouteImport.update({
  id: '/api/scorm/launch',
  path: '/api/scorm/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScormLaunchesRoute = ApiScormLaunchesRouteImport.update({
  id: '/api/scorm/launches',
  path: '/api/scorm/launches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsInstancesEventOccurrenceIdRoute =
  AdminEventsInstancesEventOccurrenceIdRouteImport.update({
    id: '/events/instances/$eventOccurrenceId',
    path: '/events/instances/$eventOccurrenceId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEventsInstancesNewRoute = AdminEventsInstancesNewRouteImport.update({
  id: '/events/instances_/new',
  path: '/events/instances/new',
  getParentRoute: () => AdminRoute,
} as any)
const ApiEventOperationsEventOccurrenceIdProgressDotcsvRoute =
  ApiEventOperationsEventOccurrenceIdProgressDotcsvRouteImport.update({
    id: '/api/event-operations/$eventOccurrenceId/progress.csv',
    path: '/api/event-operations/$eventOccurrenceId/progress.csv',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEventSurveysPublicReferenceQrDotsvgRoute =
  ApiEventSurveysPublicReferenceQrDotsvgRouteImport.update({
    id: '/api/event-surveys/$publicReference/qr.svg',
    path: '/api/event-surveys/$publicReference/qr.svg',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLearningCertificatesEnrollmentIdRoute =
  ApiLearningCertificatesEnrollmentIdRouteImport.update({
    id: '/api/learning/certificates/$enrollmentId',
    path: '/api/learning/certificates/$enrollmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLearningEventCertificatesEventParticipationIdRoute =
  ApiLearningEventCertificatesEventParticipationIdRouteImport.update({
    id: '/api/learning/event-certificates/$eventParticipationId',
    path: '/api/learning/event-certificates/$eventParticipationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLearningResourcesResourceVersionIdRoute =
  ApiLearningResourcesResourceVersionIdRouteImport.update({
    id: '/api/learning/resources/$resourceVersionId',
    path: '/api/learning/resources/$resourceVersionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiScormAttemptsAttemptIdRoute =
  ApiScormAttemptsAttemptIdRouteImport.update({
    id: '/api/scorm/attempts/$attemptId',
    path: '/api/scorm/attempts/$attemptId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRoute =
  EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRouteImport.update(
    {
      id: '/$eventOccurrenceId_/survey-qr/$eventSurveyAccessId',
      path: '/$eventOccurrenceId/survey-qr/$eventSurveyAccessId',
      getParentRoute: () => EventOperationsRoute,
    } as any,
  )
const LearnEnrollmentIdSurveysCourseVersionItemIdRoute =
  LearnEnrollmentIdSurveysCourseVersionItemIdRouteImport.update({
    id: '/learn/$enrollmentId_/surveys/$courseVersionItemId',
    path: '/learn/$enrollmentId/surveys/$courseVersionItemId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRoute =
  MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRouteImport.update({
    id: '/my-events_/$eventOccurrenceId_/surveys/$eventTemplateVersionItemId',
    path: '/my-events/$eventOccurrenceId/surveys/$eventTemplateVersionItemId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminLearnersUserIdEnrollmentsEnrollmentIdRoute =
  AdminLearnersUserIdEnrollmentsEnrollmentIdRouteImport.update({
    id: '/learners/$userId_/enrollments/$enrollmentId',
    path: '/learners/$userId/enrollments/$enrollmentId',
    getParentRoute: () => AdminRoute,
  } as any)
const ApiScormAttemptsAttemptIdContentSplatRoute =
  ApiScormAttemptsAttemptIdContentSplatRouteImport.update({
    id: '/content/$',
    path: '/content/$',
    getParentRoute: () => ApiScormAttemptsAttemptIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/event-operations': typeof EventOperationsRouteWithChildren
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/onboarding': typeof OnboardingRoute
  '/account/setup': typeof AccountSetupRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/api/health': typeof ApiHealthRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/event-operations/$eventOccurrenceId': typeof EventOperationsEventOccurrenceIdRoute
  '/event-surveys/$publicReference': typeof EventSurveysPublicReferenceRoute
  '/learn/$enrollmentId': typeof LearnEnrollmentIdRoute
  '/my-events/$eventOccurrenceId': typeof MyEventsEventOccurrenceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/event-operations/': typeof EventOperationsIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/events/$eventTemplateId': typeof AdminEventsEventTemplateIdRoute
  '/admin/events/scheduled': typeof AdminEventsScheduledRoute
  '/admin/events/settings': typeof AdminEventsSettingsRoute
  '/admin/events/templates': typeof AdminEventsTemplatesRoute
  '/admin/learners/$userId': typeof AdminLearnersUserIdRoute
  '/admin/surveys/$surveyId': typeof AdminSurveysSurveyIdRoute
  '/api/admin/resources': typeof ApiAdminResourcesRoute
  '/api/admin/scorm-packages': typeof ApiAdminScormPackagesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/scorm/launch': typeof ApiScormLaunchRoute
  '/api/scorm/launches': typeof ApiScormLaunchesRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/learners/': typeof AdminLearnersIndexRoute
  '/admin/surveys/': typeof AdminSurveysIndexRoute
  '/admin/events/instances/$eventOccurrenceId': typeof AdminEventsInstancesEventOccurrenceIdRoute
  '/admin/events/instances/new': typeof AdminEventsInstancesNewRoute
  '/api/event-operations/$eventOccurrenceId/progress.csv': typeof ApiEventOperationsEventOccurrenceIdProgressDotcsvRoute
  '/api/event-surveys/$publicReference/qr.svg': typeof ApiEventSurveysPublicReferenceQrDotsvgRoute
  '/api/learning/certificates/$enrollmentId': typeof ApiLearningCertificatesEnrollmentIdRoute
  '/api/learning/event-certificates/$eventParticipationId': typeof ApiLearningEventCertificatesEventParticipationIdRoute
  '/api/learning/resources/$resourceVersionId': typeof ApiLearningResourcesResourceVersionIdRoute
  '/api/scorm/attempts/$attemptId': typeof ApiScormAttemptsAttemptIdRouteWithChildren
  '/event-operations/$eventOccurrenceId/survey-qr/$eventSurveyAccessId': typeof EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRoute
  '/learn/$enrollmentId/surveys/$courseVersionItemId': typeof LearnEnrollmentIdSurveysCourseVersionItemIdRoute
  '/my-events/$eventOccurrenceId/surveys/$eventTemplateVersionItemId': typeof MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRoute
  '/admin/learners/$userId/enrollments/$enrollmentId': typeof AdminLearnersUserIdEnrollmentsEnrollmentIdRoute
  '/api/scorm/attempts/$attemptId/content/$': typeof ApiScormAttemptsAttemptIdContentSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/onboarding': typeof OnboardingRoute
  '/account/setup': typeof AccountSetupRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/api/health': typeof ApiHealthRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/event-operations/$eventOccurrenceId': typeof EventOperationsEventOccurrenceIdRoute
  '/event-surveys/$publicReference': typeof EventSurveysPublicReferenceRoute
  '/learn/$enrollmentId': typeof LearnEnrollmentIdRoute
  '/my-events/$eventOccurrenceId': typeof MyEventsEventOccurrenceIdRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/event-operations': typeof EventOperationsIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/events/$eventTemplateId': typeof AdminEventsEventTemplateIdRoute
  '/admin/events/scheduled': typeof AdminEventsScheduledRoute
  '/admin/events/settings': typeof AdminEventsSettingsRoute
  '/admin/events/templates': typeof AdminEventsTemplatesRoute
  '/admin/learners/$userId': typeof AdminLearnersUserIdRoute
  '/admin/surveys/$surveyId': typeof AdminSurveysSurveyIdRoute
  '/api/admin/resources': typeof ApiAdminResourcesRoute
  '/api/admin/scorm-packages': typeof ApiAdminScormPackagesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/scorm/launch': typeof ApiScormLaunchRoute
  '/api/scorm/launches': typeof ApiScormLaunchesRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/learners': typeof AdminLearnersIndexRoute
  '/admin/surveys': typeof AdminSurveysIndexRoute
  '/admin/events/instances/$eventOccurrenceId': typeof AdminEventsInstancesEventOccurrenceIdRoute
  '/admin/events/instances/new': typeof AdminEventsInstancesNewRoute
  '/api/event-operations/$eventOccurrenceId/progress.csv': typeof ApiEventOperationsEventOccurrenceIdProgressDotcsvRoute
  '/api/event-surveys/$publicReference/qr.svg': typeof ApiEventSurveysPublicReferenceQrDotsvgRoute
  '/api/learning/certificates/$enrollmentId': typeof ApiLearningCertificatesEnrollmentIdRoute
  '/api/learning/event-certificates/$eventParticipationId': typeof ApiLearningEventCertificatesEventParticipationIdRoute
  '/api/learning/resources/$resourceVersionId': typeof ApiLearningResourcesResourceVersionIdRoute
  '/api/scorm/attempts/$attemptId': typeof ApiScormAttemptsAttemptIdRouteWithChildren
  '/event-operations/$eventOccurrenceId/survey-qr/$eventSurveyAccessId': typeof EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRoute
  '/learn/$enrollmentId/surveys/$courseVersionItemId': typeof LearnEnrollmentIdSurveysCourseVersionItemIdRoute
  '/my-events/$eventOccurrenceId/surveys/$eventTemplateVersionItemId': typeof MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRoute
  '/admin/learners/$userId/enrollments/$enrollmentId': typeof AdminLearnersUserIdEnrollmentsEnrollmentIdRoute
  '/api/scorm/attempts/$attemptId/content/$': typeof ApiScormAttemptsAttemptIdContentSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/event-operations': typeof EventOperationsRouteWithChildren
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/onboarding': typeof OnboardingRoute
  '/account/setup': typeof AccountSetupRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/api/health': typeof ApiHealthRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/event-operations/$eventOccurrenceId': typeof EventOperationsEventOccurrenceIdRoute
  '/event-surveys/$publicReference': typeof EventSurveysPublicReferenceRoute
  '/learn/$enrollmentId': typeof LearnEnrollmentIdRoute
  '/my-events_/$eventOccurrenceId': typeof MyEventsEventOccurrenceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/event-operations/': typeof EventOperationsIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/events/$eventTemplateId': typeof AdminEventsEventTemplateIdRoute
  '/admin/events/scheduled': typeof AdminEventsScheduledRoute
  '/admin/events/settings': typeof AdminEventsSettingsRoute
  '/admin/events/templates': typeof AdminEventsTemplatesRoute
  '/admin/learners/$userId': typeof AdminLearnersUserIdRoute
  '/admin/surveys/$surveyId': typeof AdminSurveysSurveyIdRoute
  '/api/admin/resources': typeof ApiAdminResourcesRoute
  '/api/admin/scorm-packages': typeof ApiAdminScormPackagesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/scorm/launch': typeof ApiScormLaunchRoute
  '/api/scorm/launches': typeof ApiScormLaunchesRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/learners/': typeof AdminLearnersIndexRoute
  '/admin/surveys/': typeof AdminSurveysIndexRoute
  '/admin/events/instances/$eventOccurrenceId': typeof AdminEventsInstancesEventOccurrenceIdRoute
  '/admin/events/instances_/new': typeof AdminEventsInstancesNewRoute
  '/api/event-operations/$eventOccurrenceId/progress.csv': typeof ApiEventOperationsEventOccurrenceIdProgressDotcsvRoute
  '/api/event-surveys/$publicReference/qr.svg': typeof ApiEventSurveysPublicReferenceQrDotsvgRoute
  '/api/learning/certificates/$enrollmentId': typeof ApiLearningCertificatesEnrollmentIdRoute
  '/api/learning/event-certificates/$eventParticipationId': typeof ApiLearningEventCertificatesEventParticipationIdRoute
  '/api/learning/resources/$resourceVersionId': typeof ApiLearningResourcesResourceVersionIdRoute
  '/api/scorm/attempts/$attemptId': typeof ApiScormAttemptsAttemptIdRouteWithChildren
  '/event-operations/$eventOccurrenceId_/survey-qr/$eventSurveyAccessId': typeof EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRoute
  '/learn/$enrollmentId_/surveys/$courseVersionItemId': typeof LearnEnrollmentIdSurveysCourseVersionItemIdRoute
  '/my-events_/$eventOccurrenceId_/surveys/$eventTemplateVersionItemId': typeof MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRoute
  '/admin/learners/$userId_/enrollments/$enrollmentId': typeof AdminLearnersUserIdEnrollmentsEnrollmentIdRoute
  '/api/scorm/attempts/$attemptId/content/$': typeof ApiScormAttemptsAttemptIdContentSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/event-operations'
    | '/login'
    | '/my-events'
    | '/onboarding'
    | '/account/setup'
    | '/admin/access'
    | '/admin/modules'
    | '/admin/onboarding'
    | '/admin/resources'
    | '/api/health'
    | '/checkout/success'
    | '/courses/$slug'
    | '/event-operations/$eventOccurrenceId'
    | '/event-surveys/$publicReference'
    | '/learn/$enrollmentId'
    | '/my-events/$eventOccurrenceId'
    | '/admin/'
    | '/courses/'
    | '/event-operations/'
    | '/admin/courses/$courseId'
    | '/admin/events/$eventTemplateId'
    | '/admin/events/scheduled'
    | '/admin/events/settings'
    | '/admin/events/templates'
    | '/admin/learners/$userId'
    | '/admin/surveys/$surveyId'
    | '/api/admin/resources'
    | '/api/admin/scorm-packages'
    | '/api/auth/$'
    | '/api/scorm/launch'
    | '/api/scorm/launches'
    | '/api/stripe/webhook'
    | '/admin/courses/'
    | '/admin/events/'
    | '/admin/learners/'
    | '/admin/surveys/'
    | '/admin/events/instances/$eventOccurrenceId'
    | '/admin/events/instances/new'
    | '/api/event-operations/$eventOccurrenceId/progress.csv'
    | '/api/event-surveys/$publicReference/qr.svg'
    | '/api/learning/certificates/$enrollmentId'
    | '/api/learning/event-certificates/$eventParticipationId'
    | '/api/learning/resources/$resourceVersionId'
    | '/api/scorm/attempts/$attemptId'
    | '/event-operations/$eventOccurrenceId/survey-qr/$eventSurveyAccessId'
    | '/learn/$enrollmentId/surveys/$courseVersionItemId'
    | '/my-events/$eventOccurrenceId/surveys/$eventTemplateVersionItemId'
    | '/admin/learners/$userId/enrollments/$enrollmentId'
    | '/api/scorm/attempts/$attemptId/content/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-events'
    | '/onboarding'
    | '/account/setup'
    | '/admin/access'
    | '/admin/modules'
    | '/admin/onboarding'
    | '/admin/resources'
    | '/api/health'
    | '/checkout/success'
    | '/courses/$slug'
    | '/event-operations/$eventOccurrenceId'
    | '/event-surveys/$publicReference'
    | '/learn/$enrollmentId'
    | '/my-events/$eventOccurrenceId'
    | '/admin'
    | '/courses'
    | '/event-operations'
    | '/admin/courses/$courseId'
    | '/admin/events/$eventTemplateId'
    | '/admin/events/scheduled'
    | '/admin/events/settings'
    | '/admin/events/templates'
    | '/admin/learners/$userId'
    | '/admin/surveys/$surveyId'
    | '/api/admin/resources'
    | '/api/admin/scorm-packages'
    | '/api/auth/$'
    | '/api/scorm/launch'
    | '/api/scorm/launches'
    | '/api/stripe/webhook'
    | '/admin/courses'
    | '/admin/events'
    | '/admin/learners'
    | '/admin/surveys'
    | '/admin/events/instances/$eventOccurrenceId'
    | '/admin/events/instances/new'
    | '/api/event-operations/$eventOccurrenceId/progress.csv'
    | '/api/event-surveys/$publicReference/qr.svg'
    | '/api/learning/certificates/$enrollmentId'
    | '/api/learning/event-certificates/$eventParticipationId'
    | '/api/learning/resources/$resourceVersionId'
    | '/api/scorm/attempts/$attemptId'
    | '/event-operations/$eventOccurrenceId/survey-qr/$eventSurveyAccessId'
    | '/learn/$enrollmentId/surveys/$courseVersionItemId'
    | '/my-events/$eventOccurrenceId/surveys/$eventTemplateVersionItemId'
    | '/admin/learners/$userId/enrollments/$enrollmentId'
    | '/api/scorm/attempts/$attemptId/content/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/event-operations'
    | '/login'
    | '/my-events'
    | '/onboarding'
    | '/account/setup'
    | '/admin/access'
    | '/admin/modules'
    | '/admin/onboarding'
    | '/admin/resources'
    | '/api/health'
    | '/checkout/success'
    | '/courses/$slug'
    | '/event-operations/$eventOccurrenceId'
    | '/event-surveys/$publicReference'
    | '/learn/$enrollmentId'
    | '/my-events_/$eventOccurrenceId'
    | '/admin/'
    | '/courses/'
    | '/event-operations/'
    | '/admin/courses/$courseId'
    | '/admin/events/$eventTemplateId'
    | '/admin/events/scheduled'
    | '/admin/events/settings'
    | '/admin/events/templates'
    | '/admin/learners/$userId'
    | '/admin/surveys/$surveyId'
    | '/api/admin/resources'
    | '/api/admin/scorm-packages'
    | '/api/auth/$'
    | '/api/scorm/launch'
    | '/api/scorm/launches'
    | '/api/stripe/webhook'
    | '/admin/courses/'
    | '/admin/events/'
    | '/admin/learners/'
    | '/admin/surveys/'
    | '/admin/events/instances/$eventOccurrenceId'
    | '/admin/events/instances_/new'
    | '/api/event-operations/$eventOccurrenceId/progress.csv'
    | '/api/event-surveys/$publicReference/qr.svg'
    | '/api/learning/certificates/$enrollmentId'
    | '/api/learning/event-certificates/$eventParticipationId'
    | '/api/learning/resources/$resourceVersionId'
    | '/api/scorm/attempts/$attemptId'
    | '/event-operations/$eventOccurrenceId_/survey-qr/$eventSurveyAccessId'
    | '/learn/$enrollmentId_/surveys/$courseVersionItemId'
    | '/my-events_/$eventOccurrenceId_/surveys/$eventTemplateVersionItemId'
    | '/admin/learners/$userId_/enrollments/$enrollmentId'
    | '/api/scorm/attempts/$attemptId/content/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  EventOperationsRoute: typeof EventOperationsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MyEventsRoute: typeof MyEventsRoute
  OnboardingRoute: typeof OnboardingRoute
  AccountSetupRoute: typeof AccountSetupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  EventSurveysPublicReferenceRoute: typeof EventSurveysPublicReferenceRoute
  LearnEnrollmentIdRoute: typeof LearnEnrollmentIdRoute
  MyEventsEventOccurrenceIdRoute: typeof MyEventsEventOccurrenceIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ApiAdminResourcesRoute: typeof ApiAdminResourcesRoute
  ApiAdminScormPackagesRoute: typeof ApiAdminScormPackagesRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiScormLaunchRoute: typeof ApiScormLaunchRoute
  ApiScormLaunchesRoute: typeof ApiScormLaunchesRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiEventOperationsEventOccurrenceIdProgressDotcsvRoute: typeof ApiEventOperationsEventOccurrenceIdProgressDotcsvRoute
  ApiEventSurveysPublicReferenceQrDotsvgRoute: typeof ApiEventSurveysPublicReferenceQrDotsvgRoute
  ApiLearningCertificatesEnrollmentIdRoute: typeof ApiLearningCertificatesEnrollmentIdRoute
  ApiLearningEventCertificatesEventParticipationIdRoute: typeof ApiLearningEventCertificatesEventParticipationIdRoute
  ApiLearningResourcesResourceVersionIdRoute: typeof ApiLearningResourcesResourceVersionIdRoute
  ApiScormAttemptsAttemptIdRoute: typeof ApiScormAttemptsAttemptIdRouteWithChildren
  LearnEnrollmentIdSurveysCourseVersionItemIdRoute: typeof LearnEnrollmentIdSurveysCourseVersionItemIdRoute
  MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRoute: typeof MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-operations': {
      id: '/event-operations'
      path: '/event-operations'
      fullPath: '/event-operations'
      preLoaderRoute: typeof EventOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/setup': {
      id: '/account/setup'
      path: '/account/setup'
      fullPath: '/account/setup'
      preLoaderRoute: typeof AccountSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modules': {
      id: '/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/onboarding': {
      id: '/admin/onboarding'
      path: '/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AdminOnboardingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-operations/': {
      id: '/event-operations/'
      path: '/'
      fullPath: '/event-operations/'
      preLoaderRoute: typeof EventOperationsIndexRouteImport
      parentRoute: typeof EventOperationsRoute
    }
    '/event-operations/$eventOccurrenceId': {
      id: '/event-operations/$eventOccurrenceId'
      path: '/$eventOccurrenceId'
      fullPath: '/event-operations/$eventOccurrenceId'
      preLoaderRoute: typeof EventOperationsEventOccurrenceIdRouteImport
      parentRoute: typeof EventOperationsRoute
    }
    '/event-surveys/$publicReference': {
      id: '/event-surveys/$publicReference'
      path: '/event-surveys/$publicReference'
      fullPath: '/event-surveys/$publicReference'
      preLoaderRoute: typeof EventSurveysPublicReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$enrollmentId': {
      id: '/learn/$enrollmentId'
      path: '/learn/$enrollmentId'
      fullPath: '/learn/$enrollmentId'
      preLoaderRoute: typeof LearnEnrollmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events_/$eventOccurrenceId': {
      id: '/my-events_/$eventOccurrenceId'
      path: '/my-events/$eventOccurrenceId'
      fullPath: '/my-events/$eventOccurrenceId'
      preLoaderRoute: typeof MyEventsEventOccurrenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/$courseId': {
      id: '/admin/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AdminCoursesCourseIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$eventTemplateId': {
      id: '/admin/events/$eventTemplateId'
      path: '/events/$eventTemplateId'
      fullPath: '/admin/events/$eventTemplateId'
      preLoaderRoute: typeof AdminEventsEventTemplateIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/scheduled': {
      id: '/admin/events/scheduled'
      path: '/events/scheduled'
      fullPath: '/admin/events/scheduled'
      preLoaderRoute: typeof AdminEventsScheduledRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/settings': {
      id: '/admin/events/settings'
      path: '/events/settings'
      fullPath: '/admin/events/settings'
      preLoaderRoute: typeof AdminEventsSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/templates': {
      id: '/admin/events/templates'
      path: '/events/templates'
      fullPath: '/admin/events/templates'
      preLoaderRoute: typeof AdminEventsTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/learners/': {
      id: '/admin/learners/'
      path: '/learners'
      fullPath: '/admin/learners/'
      preLoaderRoute: typeof AdminLearnersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/learners/$userId': {
      id: '/admin/learners/$userId'
      path: '/learners/$userId'
      fullPath: '/admin/learners/$userId'
      preLoaderRoute: typeof AdminLearnersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/surveys/': {
      id: '/admin/surveys/'
      path: '/surveys'
      fullPath: '/admin/surveys/'
      preLoaderRoute: typeof AdminSurveysIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/surveys/$surveyId': {
      id: '/admin/surveys/$surveyId'
      path: '/surveys/$surveyId'
      fullPath: '/admin/surveys/$surveyId'
      preLoaderRoute: typeof AdminSurveysSurveyIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/resources': {
      id: '/api/admin/resources'
      path: '/api/admin/resources'
      fullPath: '/api/admin/resources'
      preLoaderRoute: typeof ApiAdminResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/scorm-packages': {
      id: '/api/admin/scorm-packages'
      path: '/api/admin/scorm-packages'
      fullPath: '/api/admin/scorm-packages'
      preLoaderRoute: typeof ApiAdminScormPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scorm/launch': {
      id: '/api/scorm/launch'
      path: '/api/scorm/launch'
      fullPath: '/api/scorm/launch'
      preLoaderRoute: typeof ApiScormLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scorm/launches': {
      id: '/api/scorm/launches'
      path: '/api/scorm/launches'
      fullPath: '/api/scorm/launches'
      preLoaderRoute: typeof ApiScormLaunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/instances/$eventOccurrenceId': {
      id: '/admin/events/instances/$eventOccurrenceId'
      path: '/events/instances/$eventOccurrenceId'
      fullPath: '/admin/events/instances/$eventOccurrenceId'
      preLoaderRoute: typeof AdminEventsInstancesEventOccurrenceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/instances_/new': {
      id: '/admin/events/instances_/new'
      path: '/events/instances/new'
      fullPath: '/admin/events/instances/new'
      preLoaderRoute: typeof AdminEventsInstancesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/event-operations/$eventOccurrenceId/progress.csv': {
      id: '/api/event-operations/$eventOccurrenceId/progress.csv'
      path: '/api/event-operations/$eventOccurrenceId/progress.csv'
      fullPath: '/api/event-operations/$eventOccurrenceId/progress.csv'
      preLoaderRoute: typeof ApiEventOperationsEventOccurrenceIdProgressDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/event-surveys/$publicReference/qr.svg': {
      id: '/api/event-surveys/$publicReference/qr.svg'
      path: '/api/event-surveys/$publicReference/qr.svg'
      fullPath: '/api/event-surveys/$publicReference/qr.svg'
      preLoaderRoute: typeof ApiEventSurveysPublicReferenceQrDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/certificates/$enrollmentId': {
      id: '/api/learning/certificates/$enrollmentId'
      path: '/api/learning/certificates/$enrollmentId'
      fullPath: '/api/learning/certificates/$enrollmentId'
      preLoaderRoute: typeof ApiLearningCertificatesEnrollmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/event-certificates/$eventParticipationId': {
      id: '/api/learning/event-certificates/$eventParticipationId'
      path: '/api/learning/event-certificates/$eventParticipationId'
      fullPath: '/api/learning/event-certificates/$eventParticipationId'
      preLoaderRoute: typeof ApiLearningEventCertificatesEventParticipationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/resources/$resourceVersionId': {
      id: '/api/learning/resources/$resourceVersionId'
      path: '/api/learning/resources/$resourceVersionId'
      fullPath: '/api/learning/resources/$resourceVersionId'
      preLoaderRoute: typeof ApiLearningResourcesResourceVersionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scorm/attempts/$attemptId': {
      id: '/api/scorm/attempts/$attemptId'
      path: '/api/scorm/attempts/$attemptId'
      fullPath: '/api/scorm/attempts/$attemptId'
      preLoaderRoute: typeof ApiScormAttemptsAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-operations/$eventOccurrenceId_/survey-qr/$eventSurveyAccessId': {
      id: '/event-operations/$eventOccurrenceId_/survey-qr/$eventSurveyAccessId'
      path: '/$eventOccurrenceId/survey-qr/$eventSurveyAccessId'
      fullPath: '/event-operations/$eventOccurrenceId/survey-qr/$eventSurveyAccessId'
      preLoaderRoute: typeof EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRouteImport
      parentRoute: typeof EventOperationsRoute
    }
    '/learn/$enrollmentId_/surveys/$courseVersionItemId': {
      id: '/learn/$enrollmentId_/surveys/$courseVersionItemId'
      path: '/learn/$enrollmentId/surveys/$courseVersionItemId'
      fullPath: '/learn/$enrollmentId/surveys/$courseVersionItemId'
      preLoaderRoute: typeof LearnEnrollmentIdSurveysCourseVersionItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events_/$eventOccurrenceId_/surveys/$eventTemplateVersionItemId': {
      id: '/my-events_/$eventOccurrenceId_/surveys/$eventTemplateVersionItemId'
      path: '/my-events/$eventOccurrenceId/surveys/$eventTemplateVersionItemId'
      fullPath: '/my-events/$eventOccurrenceId/surveys/$eventTemplateVersionItemId'
      preLoaderRoute: typeof MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/learners/$userId_/enrollments/$enrollmentId': {
      id: '/admin/learners/$userId_/enrollments/$enrollmentId'
      path: '/learners/$userId/enrollments/$enrollmentId'
      fullPath: '/admin/learners/$userId/enrollments/$enrollmentId'
      preLoaderRoute: typeof AdminLearnersUserIdEnrollmentsEnrollmentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/scorm/attempts/$attemptId/content/$': {
      id: '/api/scorm/attempts/$attemptId/content/$'
      path: '/content/$'
      fullPath: '/api/scorm/attempts/$attemptId/content/$'
      preLoaderRoute: typeof ApiScormAttemptsAttemptIdContentSplatRouteImport
      parentRoute: typeof ApiScormAttemptsAttemptIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccessRoute: typeof AdminAccessRoute
  AdminModulesRoute: typeof AdminModulesRoute
  AdminOnboardingRoute: typeof AdminOnboardingRoute
  AdminResourcesRoute: typeof AdminResourcesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCoursesCourseIdRoute: typeof AdminCoursesCourseIdRoute
  AdminEventsEventTemplateIdRoute: typeof AdminEventsEventTemplateIdRoute
  AdminEventsScheduledRoute: typeof AdminEventsScheduledRoute
  AdminEventsSettingsRoute: typeof AdminEventsSettingsRoute
  AdminEventsTemplatesRoute: typeof AdminEventsTemplatesRoute
  AdminLearnersUserIdRoute: typeof AdminLearnersUserIdRoute
  AdminSurveysSurveyIdRoute: typeof AdminSurveysSurveyIdRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminLearnersIndexRoute: typeof AdminLearnersIndexRoute
  AdminSurveysIndexRoute: typeof AdminSurveysIndexRoute
  AdminEventsInstancesEventOccurrenceIdRoute: typeof AdminEventsInstancesEventOccurrenceIdRoute
  AdminEventsInstancesNewRoute: typeof AdminEventsInstancesNewRoute
  AdminLearnersUserIdEnrollmentsEnrollmentIdRoute: typeof AdminLearnersUserIdEnrollmentsEnrollmentIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessRoute: AdminAccessRoute,
  AdminModulesRoute: AdminModulesRoute,
  AdminOnboardingRoute: AdminOnboardingRoute,
  AdminResourcesRoute: AdminResourcesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCoursesCourseIdRoute: AdminCoursesCourseIdRoute,
  AdminEventsEventTemplateIdRoute: AdminEventsEventTemplateIdRoute,
  AdminEventsScheduledRoute: AdminEventsScheduledRoute,
  AdminEventsSettingsRoute: AdminEventsSettingsRoute,
  AdminEventsTemplatesRoute: AdminEventsTemplatesRoute,
  AdminLearnersUserIdRoute: AdminLearnersUserIdRoute,
  AdminSurveysSurveyIdRoute: AdminSurveysSurveyIdRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminLearnersIndexRoute: AdminLearnersIndexRoute,
  AdminSurveysIndexRoute: AdminSurveysIndexRoute,
  AdminEventsInstancesEventOccurrenceIdRoute:
    AdminEventsInstancesEventOccurrenceIdRoute,
  AdminEventsInstancesNewRoute: AdminEventsInstancesNewRoute,
  AdminLearnersUserIdEnrollmentsEnrollmentIdRoute:
    AdminLearnersUserIdEnrollmentsEnrollmentIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EventOperationsRouteChildren {
  EventOperationsEventOccurrenceIdRoute: typeof EventOperationsEventOccurrenceIdRoute
  EventOperationsIndexRoute: typeof EventOperationsIndexRoute
  EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRoute: typeof EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRoute
}

const EventOperationsRouteChildren: EventOperationsRouteChildren = {
  EventOperationsEventOccurrenceIdRoute: EventOperationsEventOccurrenceIdRoute,
  EventOperationsIndexRoute: EventOperationsIndexRoute,
  EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRoute:
    EventOperationsEventOccurrenceIdSurveyQrEventSurveyAccessIdRoute,
}

const EventOperationsRouteWithChildren = EventOperationsRoute._addFileChildren(
  EventOperationsRouteChildren,
)

interface ApiScormAttemptsAttemptIdRouteChildren {
  ApiScormAttemptsAttemptIdContentSplatRoute: typeof ApiScormAttemptsAttemptIdContentSplatRoute
}

const ApiScormAttemptsAttemptIdRouteChildren: ApiScormAttemptsAttemptIdRouteChildren =
  {
    ApiScormAttemptsAttemptIdContentSplatRoute:
      ApiScormAttemptsAttemptIdContentSplatRoute,
  }

const ApiScormAttemptsAttemptIdRouteWithChildren =
  ApiScormAttemptsAttemptIdRoute._addFileChildren(
    ApiScormAttemptsAttemptIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  EventOperationsRoute: EventOperationsRouteWithChildren,
  LoginRoute: LoginRoute,
  MyEventsRoute: MyEventsRoute,
  OnboardingRoute: OnboardingRoute,
  AccountSetupRoute: AccountSetupRoute,
  ApiHealthRoute: ApiHealthRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  EventSurveysPublicReferenceRoute: EventSurveysPublicReferenceRoute,
  LearnEnrollmentIdRoute: LearnEnrollmentIdRoute,
  MyEventsEventOccurrenceIdRoute: MyEventsEventOccurrenceIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ApiAdminResourcesRoute: ApiAdminResourcesRoute,
  ApiAdminScormPackagesRoute: ApiAdminScormPackagesRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiScormLaunchRoute: ApiScormLaunchRoute,
  ApiScormLaunchesRoute: ApiScormLaunchesRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiEventOperationsEventOccurrenceIdProgressDotcsvRoute:
    ApiEventOperationsEventOccurrenceIdProgressDotcsvRoute,
  ApiEventSurveysPublicReferenceQrDotsvgRoute:
    ApiEventSurveysPublicReferenceQrDotsvgRoute,
  ApiLearningCertificatesEnrollmentIdRoute:
    ApiLearningCertificatesEnrollmentIdRoute,
  ApiLearningEventCertificatesEventParticipationIdRoute:
    ApiLearningEventCertificatesEventParticipationIdRoute,
  ApiLearningResourcesResourceVersionIdRoute:
    ApiLearningResourcesResourceVersionIdRoute,
  ApiScormAttemptsAttemptIdRoute: ApiScormAttemptsAttemptIdRouteWithChildren,
  LearnEnrollmentIdSurveysCourseVersionItemIdRoute:
    LearnEnrollmentIdSurveysCourseVersionItemIdRoute,
  MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRoute:
    MyEventsEventOccurrenceIdSurveysEventTemplateVersionItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
