/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminModulesRouteImport } from './routes/admin.modules'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as LearnEnrollmentIdRouteImport } from './routes/learn.$enrollmentId'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin.courses.index'
import { Route as AdminCoursesCourseIdRouteImport } from './routes/admin.courses.$courseId'
import { Route as AdminLearnersIndexRouteImport } from './routes/admin.learners.index'
import { Route as AdminLearnersUserIdRouteImport } from './routes/admin.learners.$userId'
import { Route as ApiAdminResourcesRouteImport } from './routes/api.admin.resources'
import { Route as ApiAdminScormPackagesRouteImport } from './routes/api.admin.scorm-packages'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiScormLaunchRouteImport } from './routes/api.scorm.launch'
import { Route as ApiScormLaunchesRouteImport } from './routes/api.scorm.launches'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'
import { Route as ApiLearningResourcesResourceVersionIdRouteImport } from './routes/api.learning.resources.$resourceVersionId'
import { Route as ApiScormAttemptsAttemptIdRouteImport } from './routes/api.scorm.attempts.$attemptId'
import { Route as AdminLearnersUserIdEnrollmentsEnrollmentIdRouteImport } from './routes/admin.learners.$userId_.enrollments.$enrollmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AdminRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnEnrollmentIdRoute = LearnEnrollmentIdRouteImport.update({
  id: '/learn/$enrollmentId',
  path: '/learn/$enrollmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesCourseIdRoute = AdminCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLearnersIndexRoute = AdminLearnersIndexRouteImport.update({
  id: '/learners/',
  path: '/learners/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLearnersUserIdRoute = AdminLearnersUserIdRouteImport.update({
  id: '/learners/$userId',
  path: '/learners/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminResourcesRoute = ApiAdminResourcesRouteImport.update({
  id: '/api/admin/resources',
  path: '/api/admin/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminScormPackagesRoute = ApiAdminScormPackagesRouteImport.update({
  id: '/api/admin/scorm-packages',
  path: '/api/admin/scorm-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScormLaunchRoute = ApiScormLaunchRouteImport.update({
  id: '/api/scorm/launch',
  path: '/api/scorm/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScormLaunchesRoute = ApiScormLaunchesRouteImport.update({
  id: '/api/scorm/launches',
  path: '/api/scorm/launches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningResourcesResourceVersionIdRoute =
  ApiLearningResourcesResourceVersionIdRouteImport.update({
    id: '/api/learning/resources/$resourceVersionId',
    path: '/api/learning/resources/$resourceVersionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiScormAttemptsAttemptIdRoute =
  ApiScormAttemptsAttemptIdRouteImport.update({
    id: '/api/scorm/attempts/$attemptId',
    path: '/api/scorm/attempts/$attemptId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminLearnersUserIdEnrollmentsEnrollmentIdRoute =
  AdminLearnersUserIdEnrollmentsEnrollmentIdRouteImport.update({
    id: '/learners/$userId_/enrollments/$enrollmentId',
    path: '/learners/$userId/enrollments/$enrollmentId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/modules': typeof AdminModulesRoute
  '/api/health': typeof ApiHealthRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/learn/$enrollmentId': typeof LearnEnrollmentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/learners/$userId': typeof AdminLearnersUserIdRoute
  '/api/admin/resources': typeof ApiAdminResourcesRoute
  '/api/admin/scorm-packages': typeof ApiAdminScormPackagesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/scorm/launch': typeof ApiScormLaunchRoute
  '/api/scorm/launches': typeof ApiScormLaunchesRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/learners/': typeof AdminLearnersIndexRoute
  '/api/learning/resources/$resourceVersionId': typeof ApiLearningResourcesResourceVersionIdRoute
  '/api/scorm/attempts/$attemptId': typeof ApiScormAttemptsAttemptIdRoute
  '/admin/learners/$userId/enrollments/$enrollmentId': typeof AdminLearnersUserIdEnrollmentsEnrollmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/modules': typeof AdminModulesRoute
  '/api/health': typeof ApiHealthRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/learn/$enrollmentId': typeof LearnEnrollmentIdRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/learners/$userId': typeof AdminLearnersUserIdRoute
  '/api/admin/resources': typeof ApiAdminResourcesRoute
  '/api/admin/scorm-packages': typeof ApiAdminScormPackagesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/scorm/launch': typeof ApiScormLaunchRoute
  '/api/scorm/launches': typeof ApiScormLaunchesRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/learners': typeof AdminLearnersIndexRoute
  '/api/learning/resources/$resourceVersionId': typeof ApiLearningResourcesResourceVersionIdRoute
  '/api/scorm/attempts/$attemptId': typeof ApiScormAttemptsAttemptIdRoute
  '/admin/learners/$userId/enrollments/$enrollmentId': typeof AdminLearnersUserIdEnrollmentsEnrollmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/modules': typeof AdminModulesRoute
  '/api/health': typeof ApiHealthRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/learn/$enrollmentId': typeof LearnEnrollmentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/learners/$userId': typeof AdminLearnersUserIdRoute
  '/api/admin/resources': typeof ApiAdminResourcesRoute
  '/api/admin/scorm-packages': typeof ApiAdminScormPackagesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/scorm/launch': typeof ApiScormLaunchRoute
  '/api/scorm/launches': typeof ApiScormLaunchesRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/learners/': typeof AdminLearnersIndexRoute
  '/api/learning/resources/$resourceVersionId': typeof ApiLearningResourcesResourceVersionIdRoute
  '/api/scorm/attempts/$attemptId': typeof ApiScormAttemptsAttemptIdRoute
  '/admin/learners/$userId_/enrollments/$enrollmentId': typeof AdminLearnersUserIdEnrollmentsEnrollmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/admin/modules'
    | '/api/health'
    | '/checkout/success'
    | '/courses/$slug'
    | '/learn/$enrollmentId'
    | '/admin/'
    | '/courses/'
    | '/admin/courses/$courseId'
    | '/admin/learners/$userId'
    | '/api/admin/resources'
    | '/api/admin/scorm-packages'
    | '/api/auth/$'
    | '/api/scorm/launch'
    | '/api/scorm/launches'
    | '/api/stripe/webhook'
    | '/admin/courses/'
    | '/admin/learners/'
    | '/api/learning/resources/$resourceVersionId'
    | '/api/scorm/attempts/$attemptId'
    | '/admin/learners/$userId/enrollments/$enrollmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/admin/modules'
    | '/api/health'
    | '/checkout/success'
    | '/courses/$slug'
    | '/learn/$enrollmentId'
    | '/admin'
    | '/courses'
    | '/admin/courses/$courseId'
    | '/admin/learners/$userId'
    | '/api/admin/resources'
    | '/api/admin/scorm-packages'
    | '/api/auth/$'
    | '/api/scorm/launch'
    | '/api/scorm/launches'
    | '/api/stripe/webhook'
    | '/admin/courses'
    | '/admin/learners'
    | '/api/learning/resources/$resourceVersionId'
    | '/api/scorm/attempts/$attemptId'
    | '/admin/learners/$userId/enrollments/$enrollmentId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/admin/modules'
    | '/api/health'
    | '/checkout/success'
    | '/courses/$slug'
    | '/learn/$enrollmentId'
    | '/admin/'
    | '/courses/'
    | '/admin/courses/$courseId'
    | '/admin/learners/$userId'
    | '/api/admin/resources'
    | '/api/admin/scorm-packages'
    | '/api/auth/$'
    | '/api/scorm/launch'
    | '/api/scorm/launches'
    | '/api/stripe/webhook'
    | '/admin/courses/'
    | '/admin/learners/'
    | '/api/learning/resources/$resourceVersionId'
    | '/api/scorm/attempts/$attemptId'
    | '/admin/learners/$userId_/enrollments/$enrollmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  LearnEnrollmentIdRoute: typeof LearnEnrollmentIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ApiAdminResourcesRoute: typeof ApiAdminResourcesRoute
  ApiAdminScormPackagesRoute: typeof ApiAdminScormPackagesRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiScormLaunchRoute: typeof ApiScormLaunchRoute
  ApiScormLaunchesRoute: typeof ApiScormLaunchesRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiLearningResourcesResourceVersionIdRoute: typeof ApiLearningResourcesResourceVersionIdRoute
  ApiScormAttemptsAttemptIdRoute: typeof ApiScormAttemptsAttemptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modules': {
      id: '/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$enrollmentId': {
      id: '/learn/$enrollmentId'
      path: '/learn/$enrollmentId'
      fullPath: '/learn/$enrollmentId'
      preLoaderRoute: typeof LearnEnrollmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/$courseId': {
      id: '/admin/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AdminCoursesCourseIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/learners/': {
      id: '/admin/learners/'
      path: '/learners'
      fullPath: '/admin/learners/'
      preLoaderRoute: typeof AdminLearnersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/learners/$userId': {
      id: '/admin/learners/$userId'
      path: '/learners/$userId'
      fullPath: '/admin/learners/$userId'
      preLoaderRoute: typeof AdminLearnersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/resources': {
      id: '/api/admin/resources'
      path: '/api/admin/resources'
      fullPath: '/api/admin/resources'
      preLoaderRoute: typeof ApiAdminResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/scorm-packages': {
      id: '/api/admin/scorm-packages'
      path: '/api/admin/scorm-packages'
      fullPath: '/api/admin/scorm-packages'
      preLoaderRoute: typeof ApiAdminScormPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scorm/launch': {
      id: '/api/scorm/launch'
      path: '/api/scorm/launch'
      fullPath: '/api/scorm/launch'
      preLoaderRoute: typeof ApiScormLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scorm/launches': {
      id: '/api/scorm/launches'
      path: '/api/scorm/launches'
      fullPath: '/api/scorm/launches'
      preLoaderRoute: typeof ApiScormLaunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/resources/$resourceVersionId': {
      id: '/api/learning/resources/$resourceVersionId'
      path: '/api/learning/resources/$resourceVersionId'
      fullPath: '/api/learning/resources/$resourceVersionId'
      preLoaderRoute: typeof ApiLearningResourcesResourceVersionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scorm/attempts/$attemptId': {
      id: '/api/scorm/attempts/$attemptId'
      path: '/api/scorm/attempts/$attemptId'
      fullPath: '/api/scorm/attempts/$attemptId'
      preLoaderRoute: typeof ApiScormAttemptsAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/learners/$userId_/enrollments/$enrollmentId': {
      id: '/admin/learners/$userId_/enrollments/$enrollmentId'
      path: '/learners/$userId/enrollments/$enrollmentId'
      fullPath: '/admin/learners/$userId/enrollments/$enrollmentId'
      preLoaderRoute: typeof AdminLearnersUserIdEnrollmentsEnrollmentIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminModulesRoute: typeof AdminModulesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCoursesCourseIdRoute: typeof AdminCoursesCourseIdRoute
  AdminLearnersUserIdRoute: typeof AdminLearnersUserIdRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminLearnersIndexRoute: typeof AdminLearnersIndexRoute
  AdminLearnersUserIdEnrollmentsEnrollmentIdRoute: typeof AdminLearnersUserIdEnrollmentsEnrollmentIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminModulesRoute: AdminModulesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCoursesCourseIdRoute: AdminCoursesCourseIdRoute,
  AdminLearnersUserIdRoute: AdminLearnersUserIdRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminLearnersIndexRoute: AdminLearnersIndexRoute,
  AdminLearnersUserIdEnrollmentsEnrollmentIdRoute:
    AdminLearnersUserIdEnrollmentsEnrollmentIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  LearnEnrollmentIdRoute: LearnEnrollmentIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ApiAdminResourcesRoute: ApiAdminResourcesRoute,
  ApiAdminScormPackagesRoute: ApiAdminScormPackagesRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiScormLaunchRoute: ApiScormLaunchRoute,
  ApiScormLaunchesRoute: ApiScormLaunchesRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiLearningResourcesResourceVersionIdRoute:
    ApiLearningResourcesResourceVersionIdRoute,
  ApiScormAttemptsAttemptIdRoute: ApiScormAttemptsAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
