import type {
  AdminEventAttendanceFilter,
  AdminEventAttendanceReport,
} from "#/features/admin-event/admin-event-operations.schema";
import {
  filterAdminEventAttendanceRows,
  hasEstimatedAttendanceEvidence,
} from "#/features/admin-event/admin-event-attendance-report";
import { encodeCsv, type CsvValue } from "./csv";

export function encodeAdminEventAttendanceCsv(
  report: AdminEventAttendanceReport,
  filters: AdminEventAttendanceFilter,
  asOf: string,
  includeHeader = true,
): string {
  const rows: Array<Array<CsvValue>> = includeHeader
    ? [
        [
          "schema_version",
          "record_type",
          "event_occurrence_id",
          "event_session_id",
          "session_title",
          "event_participation_id",
          "participant_name",
          "participant_email",
          "participation_mode",
          "attendance_state",
          "attendance_source",
          "attendance_recorded_by",
          "attendance_recorded_at",
          "attendance_updated_at",
          "decision_id",
          "decision_room_generation",
          "decision_state",
          "attendance_mode",
          "attendance_minimum_minutes",
          "qualifying_connected_seconds",
          "calculation_version",
          "decision_at",
          "application_outcome",
          "previous_attendance_state",
          "previous_attendance_source",
          "interval_id",
          "interval_room_generation",
          "joined_at",
          "joined_source",
          "left_at",
          "left_source",
          "estimated_evidence_present",
          "as_of",
        ],
      ]
    : [];
  for (const row of filterAdminEventAttendanceRows(report.rows, filters)) {
    const shared: Array<CsvValue> = [
      "event-attendance-evidence-v1",
      "attendance",
      report.occurrence.id,
      row.eventSessionId,
      row.sessionTitle,
      row.eventParticipationId,
      row.name,
      row.email,
      row.participationMode,
      row.state,
      row.source,
      row.recordedByName,
      row.recordedAt,
      row.updatedAt,
    ];
    rows.push([
      ...shared,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      hasEstimatedAttendanceEvidence(row),
      asOf,
    ]);
    for (const decision of row.decisions)
      rows.push([
        ...shared.with(1, "decision"),
        decision.id,
        decision.roomGeneration,
        decision.attendanceState,
        decision.attendanceMode,
        decision.attendanceMinimumMinutes,
        decision.qualifyingConnectedSeconds,
        decision.calculationVersion,
        decision.decisionAt,
        decision.applicationOutcome,
        decision.previousAttendanceState,
        decision.previousAttendanceSource,
        null,
        null,
        null,
        null,
        null,
        null,
        hasEstimatedAttendanceEvidence(row),
        asOf,
      ]);
    for (const interval of row.intervals)
      rows.push([
        ...shared.with(1, "interval"),
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        interval.id,
        interval.roomGeneration,
        interval.joinedAt,
        interval.joinedSource,
        interval.leftAt,
        interval.leftSource,
        hasEstimatedAttendanceEvidence(row),
        asOf,
      ]);
  }
  return encodeCsv(rows);
}
